import type { WikiArticle, WikiLang } from './wiki.types';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const ARTICLES: WikiArticle[] = [
  // ─── QUICKSTART ────────────────────────────────────────────────────────────
  {
    id: 'quickstart',
    icon: '🚀',
    category: 'start',
    title: {
      fr: 'Démarrage rapide',
      en: 'Quick Start',
      de: 'Schnellstart',
      es: 'Inicio rápido',
      'zh-HK': '快速入門',
      br: 'Kregiñ buan',
      ca: 'Inici ràpid',
    },
    content: {
      fr: [
        { type: 'p', text: 'BellePoule Modern est un logiciel de gestion de tournois d\'escrime. Il prend en charge les poules, les tableaux d\'élimination directe et la saisie distante via tablette.' },
        { type: 'h2', text: 'Flux de travail standard' },
        { type: 'ol', items: [
          'Créer une compétition (arme, catégorie, genre)',
          'Ajouter les tireurs dans l\'onglet Appel et les pointer',
          'Générer les poules et saisir les scores',
          'Valider le classement des poules → accès au Tableau',
          'Saisir les scores du tableau jusqu\'à la finale',
          'Consulter les Résultats et exporter le classement final',
        ]},
        { type: 'h2', text: 'Raccourcis indispensables' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Palette de commandes (recherche rapide)' },
          { key: '?', desc: 'Aide des raccourcis clavier' },
          { key: 'Ctrl+N', desc: 'Nouvelle compétition' },
          { key: 'Échap', desc: 'Fermer une fenêtre / Annuler' },
        ]},
        { type: 'tip', text: 'Utilisez Ctrl+K pour naviguer rapidement entre les compétitions ouvertes, accéder aux paramètres ou créer une nouvelle compétition.' },
      ],
      en: [
        { type: 'p', text: 'BellePoule Modern is a fencing tournament management software. It handles pools, direct elimination brackets, and remote scoring via tablets.' },
        { type: 'h2', text: 'Standard Workflow' },
        { type: 'ol', items: [
          'Create a competition (weapon, category, gender)',
          'Add fencers in the Check-in tab and mark them present',
          'Generate pools and enter scores',
          'Validate pool ranking → access to the Bracket',
          'Enter bracket scores up to the final',
          'View Results and export the final ranking',
        ]},
        { type: 'h2', text: 'Essential Shortcuts' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Command palette (quick search)' },
          { key: '?', desc: 'Keyboard shortcuts help' },
          { key: 'Ctrl+N', desc: 'New competition' },
          { key: 'Esc', desc: 'Close window / Cancel' },
        ]},
        { type: 'tip', text: 'Use Ctrl+K to quickly navigate between open competitions, access settings, or create a new competition.' },
      ],
      de: [
        { type: 'p', text: 'BellePoule Modern ist eine Software zur Verwaltung von Fechtturnieren. Sie unterstützt Pools, direkte Ausscheidungsrunden und Fernwertung via Tablet.' },
        { type: 'h2', text: 'Standardablauf' },
        { type: 'ol', items: [
          'Wettkampf erstellen (Waffe, Kategorie, Geschlecht)',
          'Fechter im Reiter „Eincheck" hinzufügen und anmelden',
          'Pools generieren und Ergebnisse eintragen',
          'Pool-Rangliste bestätigen → Zugang zur Ausscheidungsrunde',
          'Ergebnisse im Tableau bis zum Finale eintragen',
          'Ergebnisse ansehen und Abschlussrangliste exportieren',
        ]},
        { type: 'h2', text: 'Wichtige Tastenkürzel' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Befehlspalette (Schnellsuche)' },
          { key: '?', desc: 'Tastenkürzel-Hilfe' },
          { key: 'Ctrl+N', desc: 'Neuer Wettkampf' },
          { key: 'Esc', desc: 'Fenster schließen / Abbrechen' },
        ]},
        { type: 'tip', text: 'Mit Ctrl+K können Sie schnell zwischen offenen Wettkämpfen wechseln, Einstellungen aufrufen oder einen neuen Wettkampf erstellen.' },
      ],
      es: [
        { type: 'p', text: 'BellePoule Modern es un software de gestión de torneos de esgrima. Gestiona poules, cuadros de eliminación directa y puntuación remota vía tablet.' },
        { type: 'h2', text: 'Flujo de trabajo estándar' },
        { type: 'ol', items: [
          'Crear una competición (arma, categoría, género)',
          'Añadir tiradores en la pestaña Inscripción y marcarlos presentes',
          'Generar poules e introducir puntuaciones',
          'Validar la clasificación de poules → acceso al Cuadro',
          'Introducir puntuaciones en el cuadro hasta la final',
          'Consultar Resultados y exportar la clasificación final',
        ]},
        { type: 'h2', text: 'Atajos esenciales' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Paleta de comandos (búsqueda rápida)' },
          { key: '?', desc: 'Ayuda de atajos de teclado' },
          { key: 'Ctrl+N', desc: 'Nueva competición' },
          { key: 'Esc', desc: 'Cerrar ventana / Cancelar' },
        ]},
        { type: 'tip', text: 'Usa Ctrl+K para navegar rápidamente entre competiciones abiertas, acceder a ajustes o crear una nueva competición.' },
      ],
      'zh-HK': [
        { type: 'p', text: 'BellePoule Modern 是一款擊劍錦標賽管理軟件，支援分組循環賽、直接淘汰賽及平板遠端記分。' },
        { type: 'h2', text: '標準流程' },
        { type: 'ol', items: [
          '建立比賽（武器、組別、性別）',
          '在「報到」分頁新增選手並標記出席',
          '生成分組並輸入成績',
          '確認分組排名 → 進入淘汰賽',
          '輸入淘汰賽成績直至決賽',
          '查看結果並匯出最終排名',
        ]},
        { type: 'h2', text: '常用快捷鍵' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: '命令面板（快速搜尋）' },
          { key: '?', desc: '鍵盤快捷鍵說明' },
          { key: 'Ctrl+N', desc: '新增比賽' },
          { key: 'Esc', desc: '關閉視窗 / 取消' },
        ]},
        { type: 'tip', text: '使用 Ctrl+K 可快速在已開啟的比賽之間切換、進入設定或建立新比賽。' },
      ],
      br: [
        { type: 'p', text: 'BellePoule Modern a zo ur meziant evit merañ kenstrivadegoù klezeouriezh. Emaog merañ poulloù, tablelloù eliminerezh direkt ha enrollañ eus-pell dre tablet.' },
        { type: 'h2', text: 'Rummad labour reizh' },
        { type: 'ol', items: [
          'Krouiñ ur genstrivadeg (arm, rummad, reizh)',
          'Ouzhpennañ klañvourien en ivinell Ergerout ha notal o c\'hourennañ',
          'Sevel poulloù ha pourvezañ notadoù',
          'Kadarnaat renk ar poulloù → tizhet ar Daolenn',
          'Pourvezañ notadoù an daolenn betek ar final',
          'Sellet ouzh ar Disoc\'hoù ha ezporzhiañ ar renk dibenn',
        ]},
        { type: 'h2', text: 'Berradurioù ret' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Palet urzhioù (klask buan)' },
          { key: '?', desc: 'Skoazell berradurioù klavier' },
          { key: 'Ctrl+N', desc: 'Kenstrivadeg nevez' },
          { key: 'Esc', desc: 'Serriñ ur prenestr / Nullañ' },
        ]},
        { type: 'tip', text: 'Implij Ctrl+K evit lezel buan etre kenstrivadegoù digor, tizout ar parametroù pe krouiñ kenstrivadeg nevez.' },
      ],
      ca: [
        { type: 'p', text: 'BellePoule Modern és un programari de gestió de tornejos d\'esgrima. Gestiona poules, quadres d\'eliminació directa i puntuació remota via tauleta.' },
        { type: 'h2', text: 'Flux de treball estàndard' },
        { type: 'ol', items: [
          'Crear una competició (arma, categoria, gènere)',
          'Afegir tiradors a la pestanya Inscripció i marcar-los com a presents',
          'Generar poules i introduir puntuacions',
          'Validar la classificació de poules → accés al Quadre',
          'Introduir puntuacions al quadre fins a la final',
          'Consultar Resultats i exportar la classificació final',
        ]},
        { type: 'h2', text: 'Dreceres essencials' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Paleta d\'ordres (cerca ràpida)' },
          { key: '?', desc: 'Ajuda de dreceres de teclat' },
          { key: 'Ctrl+N', desc: 'Nova competició' },
          { key: 'Esc', desc: 'Tancar finestra / Cancel·lar' },
        ]},
        { type: 'tip', text: 'Utilitza Ctrl+K per navegar ràpidament entre competicions obertes, accedir a la configuració o crear una nova competició.' },
      ],
    },
  },

  // ─── COMPETITION ───────────────────────────────────────────────────────────
  {
    id: 'competition',
    icon: '🏆',
    category: 'competition',
    title: {
      fr: 'Créer une compétition',
      en: 'Create a Competition',
      de: 'Wettkampf erstellen',
      es: 'Crear una competición',
      'zh-HK': '建立比賽',
      br: 'Krouiñ ur genstrivadeg',
      ca: 'Crear una competició',
    },
    content: {
      fr: [
        { type: 'p', text: 'Une compétition est définie par son arme, son genre et sa catégorie. Ces paramètres déterminent les règles de scoring et les formules disponibles.' },
        { type: 'h2', text: 'Armes disponibles' },
        { type: 'ul', items: [
          '⚔️ Épée — touche n\'importe où, score max 15 par défaut',
          '🤺 Fleuret — cible limitée au torse, scoring standard',
          '🗡️ Sabre — touche au-dessus de la ceinture, scoring rapide',
          '⚡ Sabre Laser — zones A/B/C avec points variables (1/3/5)',
          '🎛️ À la carte — formule entièrement personnalisable',
        ]},
        { type: 'h2', text: 'Catégories' },
        { type: 'ul', items: [
          'Poussins (U11), Benjamins (U13), Minimes (U15)',
          'Cadets (U17), Juniors (U20), Seniors',
          'Vétérans V1 à V4',
        ]},
        { type: 'h2', text: 'Formules' },
        { type: 'p', text: 'BellePoule propose des formules prédéfinies adaptées au nombre de tireurs. Vous pouvez aussi utiliser le Constructeur de formule pour créer des enchaînements de phases (poules → tableau → classement) avec des règles d\'avancement personnalisées.' },
        { type: 'tip', text: 'La couleur de compétition aide à distinguer les onglets lorsque plusieurs compétitions sont ouvertes simultanément.' },
      ],
      en: [
        { type: 'p', text: 'A competition is defined by its weapon, gender, and category. These parameters determine scoring rules and available formulas.' },
        { type: 'h2', text: 'Available Weapons' },
        { type: 'ul', items: [
          '⚔️ Epee — touch anywhere, default max score 15',
          '🤺 Foil — target limited to torso, standard scoring',
          '🗡️ Sabre — touches above the waist, fast scoring',
          '⚡ Laser Sabre — zones A/B/C with variable points (1/3/5)',
          '🎛️ Custom — fully customizable formula',
        ]},
        { type: 'h2', text: 'Categories' },
        { type: 'ul', items: [
          'U11, U13, U15 (Youth)',
          'U17 (Cadet), U20 (Junior), Senior',
          'Veterans V1 to V4',
        ]},
        { type: 'h2', text: 'Formulas' },
        { type: 'p', text: 'BellePoule provides predefined formulas adapted to the number of fencers. You can also use the Formula Builder to create phase sequences (pools → bracket → ranking) with custom advancement rules.' },
        { type: 'tip', text: 'The competition color helps distinguish tabs when multiple competitions are open simultaneously.' },
      ],
      de: [
        { type: 'p', text: 'Ein Wettkampf wird durch Waffe, Geschlecht und Kategorie definiert. Diese Parameter bestimmen die Wertungsregeln und verfügbaren Formeln.' },
        { type: 'h2', text: 'Verfügbare Waffen' },
        { type: 'ul', items: [
          '⚔️ Degen — Treffer überall, Standard-Höchstpunktzahl 15',
          '🤺 Florett — Trefferfläche auf den Rumpf begrenzt',
          '🗡️ Säbel — Treffer oberhalb der Taille, schnelle Wertung',
          '⚡ Lasersäbel — Zonen A/B/C mit variablen Punkten (1/3/5)',
          '🎛️ Benutzerdefiniert — vollständig anpassbare Formel',
        ]},
        { type: 'h2', text: 'Kategorien' },
        { type: 'ul', items: [
          'U11, U13, U15 (Jugend)',
          'U17 (Kadett), U20 (Junior), Senior',
          'Veteranen V1 bis V4',
        ]},
        { type: 'h2', text: 'Formeln' },
        { type: 'p', text: 'BellePoule bietet vordefinierte Formeln je nach Fechteranzahl. Mit dem Formel-Builder können Sie Phasenabfolgen (Pools → Tableau → Rangliste) mit benutzerdefinierten Aufstiegsregeln erstellen.' },
        { type: 'tip', text: 'Die Wettkampffarbe hilft, Reiter zu unterscheiden, wenn mehrere Wettkämpfe gleichzeitig geöffnet sind.' },
      ],
      es: [
        { type: 'p', text: 'Una competición se define por su arma, género y categoría. Estos parámetros determinan las reglas de puntuación y las fórmulas disponibles.' },
        { type: 'h2', text: 'Armas disponibles' },
        { type: 'ul', items: [
          '⚔️ Espada — toque en cualquier lugar, puntuación máx. 15 por defecto',
          '🤺 Florete — blanco limitado al torso, puntuación estándar',
          '🗡️ Sable — toques por encima de la cintura, puntuación rápida',
          '⚡ Sable Láser — zonas A/B/C con puntos variables (1/3/5)',
          '🎛️ Personalizado — fórmula completamente configurable',
        ]},
        { type: 'h2', text: 'Categorías' },
        { type: 'ul', items: [
          'Sub-11, Sub-13, Sub-15 (Infantil/Benjamín)',
          'Sub-17 (Cadete), Sub-20 (Junior), Sénior',
          'Veteranos V1 a V4',
        ]},
        { type: 'h2', text: 'Fórmulas' },
        { type: 'p', text: 'BellePoule ofrece fórmulas predefinidas adaptadas al número de tiradores. También puedes usar el Constructor de fórmulas para crear secuencias de fases (poules → cuadro → clasificación) con reglas de avance personalizadas.' },
        { type: 'tip', text: 'El color de competición ayuda a distinguir las pestañas cuando hay varias competiciones abiertas simultáneamente.' },
      ],
      'zh-HK': [
        { type: 'p', text: '比賽由武器、性別和組別定義，這些參數決定計分規則和可用賽制。' },
        { type: 'h2', text: '可用武器' },
        { type: 'ul', items: [
          '⚔️ 重劍 — 全身有效，預設最高分 15',
          '🤺 花劍 — 有效部位限軀幹，標準計分',
          '🗡️ 軍刀 — 腰以上有效，快速計分',
          '⚡ 激光軍刀 — A/B/C 區域，可變分值（1/3/5）',
          '🎛️ 自訂 — 完全可配置賽制',
        ]},
        { type: 'h2', text: '組別' },
        { type: 'ul', items: [
          'U11、U13、U15（青少年）',
          'U17（少年）、U20（青年）、成年',
          '老將 V1 至 V4',
        ]},
        { type: 'h2', text: '賽制' },
        { type: 'p', text: 'BellePoule 提供根據選手人數預設的賽制。您也可使用賽制生成器建立自訂賽段序列（分組→淘汰賽→排名），並設定晉級規則。' },
        { type: 'tip', text: '比賽顏色有助於在多個比賽同時開啟時區分分頁。' },
      ],
      br: [
        { type: 'p', text: 'Un genstrivadeg a zo miret dre e arm, e reizh hag e rummad. An parametroù-se a zizoloù reolioù an notadeg hag ar formulaoù hegerz.' },
        { type: 'h2', text: 'Armoù hegerz' },
        { type: 'ul', items: [
          '⚔️ Klezeeg — pouez e feur-lec\'h, notadenn uhelañ 15 dre ziouer',
          '🤺 Floret — tachenn rediataet d\'ar c\'horf',
          '🗡️ Gouriz — pouez dreist ar gouriz, notadeg buan',
          '⚡ Gouriz Laser — zonoù A/B/C gant poentoù kemmadus (1/3/5)',
          '🎛️ Diboell — formula personalizet a-bezh',
        ]},
        { type: 'h2', text: 'Rummadoù' },
        { type: 'ul', items: [
          'U11, U13, U15 (Yaouankiz)',
          'U17 (Kadet), U20 (Junior), Senior',
          'Veteraned V1 da V4',
        ]},
        { type: 'h2', text: 'Formulaoù' },
        { type: 'p', text: 'BellePoule a ro formulaoù rakdifinet degaset d\'an niver a glañvourien. Gallout a rit ivez implijout ar Savour Formula da grouiñ rummadoù fazioù (poulloù → daolenn → renk) gant reolioù personalizet.' },
        { type: 'tip', text: 'Liv ur genstrivadeg a skoazell da rannañ an ivinelloù pa vez kalz kenstrivadegoù digor war un dro.' },
      ],
      ca: [
        { type: 'p', text: 'Una competició es defineix per la seva arma, gènere i categoria. Aquests paràmetres determinen les regles de puntuació i les fórmules disponibles.' },
        { type: 'h2', text: 'Armes disponibles' },
        { type: 'ul', items: [
          '⚔️ Espasa — toc a qualsevol lloc, puntuació màx. 15 per defecte',
          '🤺 Floret — blanc limitat al tors, puntuació estàndard',
          '🗡️ Sabre — tocs per sobre la cintura, puntuació ràpida',
          '⚡ Sabre Làser — zones A/B/C amb punts variables (1/3/5)',
          '🎛️ Personalitzat — fórmula completament configurable',
        ]},
        { type: 'h2', text: 'Categories' },
        { type: 'ul', items: [
          'U11, U13, U15 (Infantil)',
          'U17 (Cadet), U20 (Junior), Sènior',
          'Veterans V1 a V4',
        ]},
        { type: 'h2', text: 'Fórmules' },
        { type: 'p', text: 'BellePoule ofereix fórmules predefinides adaptades al nombre de tiradors. També podeu fer servir el Constructor de fórmules per crear seqüències de fases (poules → quadre → classificació) amb regles d\'avanç personalitzades.' },
        { type: 'tip', text: 'El color de competició ajuda a distingir les pestanyes quan hi ha diverses competicions obertes simultàniament.' },
      ],
    },
  },

  // ─── CHECK-IN ───────────────────────────────────────────────────────────────
  {
    id: 'checkin',
    icon: '✅',
    category: 'competition',
    title: {
      fr: 'Phase d\'Appel',
      en: 'Check-in Phase',
      de: 'Eincheck-Phase',
      es: 'Fase de Inscripción',
      'zh-HK': '報到階段',
      br: 'Traoù Ergerout',
      ca: 'Fase d\'Inscripció',
    },
    content: {
      fr: [
        { type: 'p', text: 'L\'Appel est la première phase. Elle permet de gérer la liste des tireurs et de confirmer leur présence avant le début de la compétition.' },
        { type: 'h2', text: 'Gestion des tireurs' },
        { type: 'ul', items: [
          'Ajouter des tireurs manuellement ou par import (CSV, XML, FFE)',
          'Pointer chaque tireur présent (coche verte)',
          '"Tout pointer" pour marquer tous les inscrits comme présents',
          'Définir le statut : Présent, Forfait, Abandon',
        ]},
        { type: 'h2', text: 'Import de tireurs' },
        { type: 'ul', items: [
          'Format CSV — colonnes : Nom, Prénom, Club, Licence, Classement',
          'Format XML — export standard FFE',
          'Format FFE Connect — connexion directe à la fédération',
        ]},
        { type: 'warning', text: 'Il faut au minimum 4 tireurs pointés pour générer les poules. Un message d\'erreur s\'affiche si ce seuil n\'est pas atteint.' },
        { type: 'h2', text: 'Statuts des tireurs' },
        { type: 'ul', items: [
          '⚪ Non pointé — inscrit mais absent',
          '🟢 Présent — pointé, participera à la compétition',
          '🔵 Qualifié — a passé les poules avec succès',
          '🔴 Éliminé — sorti du tableau',
          '⚫ Forfait / Abandon — retiré de la compétition',
        ]},
      ],
      en: [
        { type: 'p', text: 'Check-in is the first phase. It manages the fencer list and confirms their presence before the competition starts.' },
        { type: 'h2', text: 'Managing Fencers' },
        { type: 'ul', items: [
          'Add fencers manually or via import (CSV, XML, FFE)',
          'Check in each present fencer (green checkmark)',
          '"Check in all" to mark all registered fencers as present',
          'Set status: Present, Forfeit, Withdrawal',
        ]},
        { type: 'h2', text: 'Fencer Import' },
        { type: 'ul', items: [
          'CSV format — columns: Last name, First name, Club, License, Ranking',
          'XML format — standard FFE export',
          'FFE Connect — direct federation connection',
        ]},
        { type: 'warning', text: 'At least 4 checked-in fencers are required to generate pools. An error message is shown if this threshold is not met.' },
        { type: 'h2', text: 'Fencer Statuses' },
        { type: 'ul', items: [
          '⚪ Not checked in — registered but absent',
          '🟢 Present — checked in, will compete',
          '🔵 Qualified — passed the pool phase',
          '🔴 Eliminated — knocked out of the bracket',
          '⚫ Forfeit / Withdrawal — removed from competition',
        ]},
      ],
      de: [
        { type: 'p', text: 'Das Eincheck ist die erste Phase. Sie verwaltet die Fechterliste und bestätigt die Anwesenheit vor Wettkampfbeginn.' },
        { type: 'h2', text: 'Fechter verwalten' },
        { type: 'ul', items: [
          'Fechter manuell oder per Import hinzufügen (CSV, XML, FFE)',
          'Jeden anwesenden Fechter einchecken (grüner Haken)',
          '„Alle einchecken" um alle Angemeldeten als anwesend zu markieren',
          'Status festlegen: Anwesend, Aufgabe, Rückzug',
        ]},
        { type: 'h2', text: 'Fechter importieren' },
        { type: 'ul', items: [
          'CSV-Format — Spalten: Nachname, Vorname, Verein, Lizenz, Rangliste',
          'XML-Format — Standard-FFE-Export',
          'FFE Connect — direkte Verbindung zum Verband',
        ]},
        { type: 'warning', text: 'Mindestens 4 eingecheckte Fechter sind erforderlich, um Pools zu generieren.' },
        { type: 'h2', text: 'Fechterstatus' },
        { type: 'ul', items: [
          '⚪ Nicht eingecheckt — angemeldet aber abwesend',
          '🟢 Anwesend — eingecheckt, nimmt teil',
          '🔵 Qualifiziert — Pool-Phase bestanden',
          '🔴 Ausgeschieden — aus dem Tableau ausgeschieden',
          '⚫ Aufgabe / Rückzug — aus dem Wettkampf zurückgezogen',
        ]},
      ],
      es: [
        { type: 'p', text: 'La inscripción es la primera fase. Gestiona la lista de tiradores y confirma su presencia antes del inicio de la competición.' },
        { type: 'h2', text: 'Gestión de tiradores' },
        { type: 'ul', items: [
          'Añadir tiradores manualmente o por importación (CSV, XML, FFE)',
          'Marcar como presente cada tirador (marca verde)',
          '"Marcar todos" para registrar a todos los inscritos como presentes',
          'Definir estado: Presente, Retirado, Abandono',
        ]},
        { type: 'h2', text: 'Importar tiradores' },
        { type: 'ul', items: [
          'Formato CSV — columnas: Apellido, Nombre, Club, Licencia, Clasificación',
          'Formato XML — exportación estándar FFE',
          'FFE Connect — conexión directa con la federación',
        ]},
        { type: 'warning', text: 'Se necesitan al menos 4 tiradores inscritos para generar las poules.' },
        { type: 'h2', text: 'Estados de los tiradores' },
        { type: 'ul', items: [
          '⚪ No inscrito — registrado pero ausente',
          '🟢 Presente — inscrito, participará',
          '🔵 Clasificado — superó la fase de poules',
          '🔴 Eliminado — fuera del cuadro',
          '⚫ Retirado / Abandono — excluido de la competición',
        ]},
      ],
      'zh-HK': [
        { type: 'p', text: '報到是第一個階段，用於管理選手名單並在比賽開始前確認出席情況。' },
        { type: 'h2', text: '管理選手' },
        { type: 'ul', items: [
          '手動新增選手或透過匯入（CSV、XML、FFE）',
          '為每位出席選手辦理報到（綠色勾選）',
          '「全部報到」可將所有已登記選手標記為出席',
          '設定狀態：出席、棄權、退賽',
        ]},
        { type: 'h2', text: '匯入選手' },
        { type: 'ul', items: [
          'CSV 格式 — 欄位：姓名、名字、俱樂部、執照、排名',
          'XML 格式 — 標準 FFE 匯出',
          'FFE Connect — 直接連接聯盟',
        ]},
        { type: 'warning', text: '生成分組至少需要 4 名已報到的選手，否則將顯示錯誤訊息。' },
        { type: 'h2', text: '選手狀態' },
        { type: 'ul', items: [
          '⚪ 未報到 — 已登記但缺席',
          '🟢 出席 — 已報到，將參賽',
          '🔵 晉級 — 通過分組賽',
          '🔴 淘汰 — 已出局',
          '⚫ 棄權 / 退賽 — 已退出比賽',
        ]},
      ],
      br: [
        { type: 'p', text: 'An Ergerout eo an traoù gentañ. Emaog merañ listenn ar c\'hlañvourien ha kadarnaat o c\'hourennañ a-raok kregiñ.' },
        { type: 'h2', text: 'Merañ klañvourien' },
        { type: 'ul', items: [
          'Ouzhpennañ klañvourien gant dorn pe dre ezporzhadur (CSV, XML, FFE)',
          'Notenañ pep klañvouer a zo (marc\'h glas)',
          '„Notenañ an holl" evit merañ an holl skrivet evel c\'hourennant',
          'Termeniñ ar stad: C\'hourennant, Enkredek, Lezel',
        ]},
        { type: 'h2', text: 'Ezporzhadur klañvourien' },
        { type: 'ul', items: [
          'Furmad CSV — kolonnelloù: Anv, Kentanv, Klub, Roadenn, Renk',
          'Furmad XML — ezporzhadur reizh FFE',
          'FFE Connect — kevreadenn resis ouzh ar gevredigezh',
        ]},
        { type: 'warning', text: 'Ret eo bet 4 klañvouer notet evit sevel ar poulloù.' },
        { type: 'h2', text: 'Stadoù klañvourien' },
        { type: 'ul', items: [
          '⚪ N\'eo ket notet — skrivet met dihamet',
          '🟢 C\'hourennant — notet, a vo er genstrivadeg',
          '🔵 Kualifiet — tre ar poulloù gant mad',
          '🔴 Eliminaet — diwar ar daolenn',
          '⚫ Enkredek / Lezel — tennit eus ar genstrivadeg',
        ]},
      ],
      ca: [
        { type: 'p', text: 'La inscripció és la primera fase. Gestiona la llista de tiradors i confirma la seva presència abans de l\'inici de la competició.' },
        { type: 'h2', text: 'Gestió de tiradors' },
        { type: 'ul', items: [
          'Afegir tiradors manualment o per importació (CSV, XML, FFE)',
          'Marcar com a present cada tirador (marca verda)',
          '„Marcar tots" per registrar tots els inscrits com a presents',
          'Definir estat: Present, Retirat, Abandonament',
        ]},
        { type: 'h2', text: 'Importar tiradors' },
        { type: 'ul', items: [
          'Format CSV — columnes: Cognom, Nom, Club, Llicència, Classificació',
          'Format XML — exportació estàndard FFE',
          'FFE Connect — connexió directa amb la federació',
        ]},
        { type: 'warning', text: 'Calen almenys 4 tiradors inscrits per generar les poules.' },
        { type: 'h2', text: 'Estats dels tiradors' },
        { type: 'ul', items: [
          '⚪ No inscrit — registrat però absent',
          '🟢 Present — inscrit, participarà',
          '🔵 Classificat — ha superat la fase de poules',
          '🔴 Eliminat — fora del quadre',
          '⚫ Retirat / Abandonament — exclòs de la competició',
        ]},
      ],
    },
  },

  // ─── POOLS ──────────────────────────────────────────────────────────────────
  {
    id: 'pools',
    icon: '🎯',
    category: 'phases',
    title: {
      fr: 'Phase de Poules',
      en: 'Pool Phase',
      de: 'Pool-Phase',
      es: 'Fase de Poules',
      'zh-HK': '分組循環賽',
      br: 'Traoù ar Poulloù',
      ca: 'Fase de Poules',
    },
    content: {
      fr: [
        { type: 'p', text: 'Les poules sont des mini-tournois en round-robin. Chaque tireur affronte tous les autres tireurs de sa poule. Le classement final détermine qui accède au tableau.' },
        { type: 'h2', text: 'Génération des poules' },
        { type: 'p', text: 'BellePoule répartit automatiquement les tireurs en poules de taille optimale selon le nombre de participants. La répartition peut être ajustée manuellement dans la phase de Préparation.' },
        { type: 'h2', text: 'Saisie des scores' },
        { type: 'ul', items: [
          'Cliquez sur une case dans la grille pour saisir le score',
          'Format : score du tireur en ligne vs tireur en colonne',
          'V = Victoire, score max configurable (défaut : 5)',
          'Le vainqueur est noté V, le perdant son score réel',
        ]},
        { type: 'h2', text: 'Critères de classement' },
        { type: 'ol', items: [
          'Ratio V/M (victoires sur matchs joués)',
          'Indice (touches données − touches reçues)',
          'Touches données (TD)',
          'Confrontation directe (en cas d\'égalité)',
          'Classement initial',
        ]},
        { type: 'h2', text: 'Tours de poules' },
        { type: 'p', text: 'Une formule peut comporter plusieurs tours de poules. Les tireurs sont redistribués entre chaque tour selon leur classement intermédiaire.' },
        { type: 'tip', text: 'La saisie distante (tablette arbitre) permet de saisir les scores en temps réel depuis les arènes pendant les poules.' },
      ],
      en: [
        { type: 'p', text: 'Pools are round-robin mini-tournaments. Each fencer faces all others in their pool. The final ranking determines who advances to the bracket.' },
        { type: 'h2', text: 'Pool Generation' },
        { type: 'p', text: 'BellePoule automatically distributes fencers into optimally-sized pools based on participant count. Distribution can be manually adjusted in the Preparation phase.' },
        { type: 'h2', text: 'Score Entry' },
        { type: 'ul', items: [
          'Click a cell in the grid to enter the score',
          'Format: row fencer\'s score vs column fencer',
          'V = Victory, configurable max score (default: 5)',
          'The winner is marked V, the loser gets their actual score',
        ]},
        { type: 'h2', text: 'Ranking Criteria' },
        { type: 'ol', items: [
          'V/M ratio (victories to bouts ratio)',
          'Index (touches scored − touches received)',
          'Touches scored (TS)',
          'Direct encounter (in case of tie)',
          'Initial seeding',
        ]},
        { type: 'h2', text: 'Pool Rounds' },
        { type: 'p', text: 'A formula can include multiple pool rounds. Fencers are redistributed between rounds based on their intermediate ranking.' },
        { type: 'tip', text: 'Remote scoring (referee tablet) allows real-time score entry from arenas during pools.' },
      ],
      de: [
        { type: 'p', text: 'Pools sind Round-Robin-Miniwettkämpfe. Jeder Fechter trifft alle anderen in seinem Pool. Die Endrangliste bestimmt, wer ins Tableau aufsteigt.' },
        { type: 'h2', text: 'Pool-Generierung' },
        { type: 'p', text: 'BellePoule verteilt Fechter automatisch in Pools optimaler Größe basierend auf der Teilnehmerzahl. Die Verteilung kann in der Vorbereitungsphase manuell angepasst werden.' },
        { type: 'h2', text: 'Ergebniseingabe' },
        { type: 'ul', items: [
          'Klicken Sie auf eine Zelle im Raster, um das Ergebnis einzugeben',
          'Format: Treffer Zeilenfechter vs. Spaltenfechter',
          'V = Sieg, konfigurierbares Höchstergebnis (Standard: 5)',
          'Der Sieger wird mit V markiert, der Verlierer mit seinem Ergebnis',
        ]},
        { type: 'h2', text: 'Ranglistenkriterien' },
        { type: 'ol', items: [
          'V/M-Verhältnis (Siege zu Gefechten)',
          'Index (gegebene − empfangene Treffer)',
          'Gegebene Treffer (GT)',
          'Direktbegegnung (bei Gleichstand)',
          'Erstrangierung',
        ]},
        { type: 'h2', text: 'Pool-Runden' },
        { type: 'p', text: 'Eine Formel kann mehrere Pool-Runden umfassen. Fechter werden zwischen den Runden nach ihrer Zwischenrangliste umverteilt.' },
        { type: 'tip', text: 'Die Fernwertung (Schiedsrichter-Tablet) ermöglicht die Echtzeiteingabe von Ergebnissen von den Pisten während der Pools.' },
      ],
      es: [
        { type: 'p', text: 'Las poules son mini-torneos de todos contra todos. Cada tirador se enfrenta a todos los demás de su grupo. La clasificación final determina quién pasa al cuadro.' },
        { type: 'h2', text: 'Generación de poules' },
        { type: 'p', text: 'BellePoule distribuye automáticamente los tiradores en grupos de tamaño óptimo según el número de participantes. La distribución puede ajustarse manualmente en la fase de Preparación.' },
        { type: 'h2', text: 'Introducción de puntuaciones' },
        { type: 'ul', items: [
          'Haz clic en una celda de la cuadrícula para introducir la puntuación',
          'Formato: puntuación del tirador en fila vs tirador en columna',
          'V = Victoria, puntuación máx. configurable (defecto: 5)',
          'El ganador se marca con V, el perdedor con su puntuación real',
        ]},
        { type: 'h2', text: 'Criterios de clasificación' },
        { type: 'ol', items: [
          'Ratio V/M (victorias sobre combates disputados)',
          'Índice (toques dados − toques recibidos)',
          'Toques dados (TD)',
          'Enfrentamiento directo (en caso de empate)',
          'Clasificación inicial',
        ]},
        { type: 'h2', text: 'Rondas de poules' },
        { type: 'p', text: 'Una fórmula puede tener varias rondas de poules. Los tiradores se redistribuyen entre rondas según su clasificación intermedia.' },
        { type: 'tip', text: 'La puntuación remota (tablet árbitro) permite introducir puntuaciones en tiempo real desde las pistas durante las poules.' },
      ],
      'zh-HK': [
        { type: 'p', text: '分組循環賽是小型循環賽，每位選手對陣同組所有其他選手，最終排名決定誰晉級淘汰賽。' },
        { type: 'h2', text: '生成分組' },
        { type: 'p', text: 'BellePoule 根據參賽人數自動將選手分配到最佳規模的分組中，也可在準備階段手動調整。' },
        { type: 'h2', text: '輸入成績' },
        { type: 'ul', items: [
          '點擊表格中的格子輸入成績',
          '格式：橫排選手成績 vs 縱排選手',
          'V = 勝利，最高分可配置（預設：5）',
          '勝者標記 V，敗者填入實際得分',
        ]},
        { type: 'h2', text: '排名標準' },
        { type: 'ol', items: [
          'V/M 比率（勝場數/出賽場數）',
          '指數（得分 − 失分）',
          '得分（TD）',
          '直接對陣（同分時）',
          '初始種子',
        ]},
        { type: 'h2', text: '分組輪次' },
        { type: 'p', text: '賽制可包含多輪分組賽，每輪後根據中間排名重新分配選手。' },
        { type: 'tip', text: '遠端記分（裁判平板）可在分組賽期間從賽場即時輸入成績。' },
      ],
      br: [
        { type: 'p', text: 'Ar poulloù a zo kenstrivadegoù bihan round-robin. Pep klañvouer a vont erbenn an holl re all e boulloù. Ar renk dibenn a ziziolo piv a ya d\'ar daolenn.' },
        { type: 'h2', text: 'Sevel ar poulloù' },
        { type: 'p', text: 'BellePoule a rann ar c\'hlañvourien ent emgefreek e poulloù eus ment reizh hervez an niver a c\'hourennourien.' },
        { type: 'h2', text: 'Pourvezañ notadoù' },
        { type: 'ul', items: [
          'Klikit war ur vuzhug er restr evit pourvezañ an notenn',
          'Furmad: notenn an tirant en linenn vs tirant en kolonnenn',
          'V = Gounid, notenn uhelañ kustomizabl (dre ziouer: 5)',
          'An treuzour a zo notet V, an trestet e notenn wir',
        ]},
        { type: 'h2', text: 'Arvesterioù renk' },
        { type: 'ol', items: [
          'Rapport V/M (gounidoù war c\'harioù c\'hoariet)',
          'Indez (pouezioù roet − pouezioù resevet)',
          'Pouezioù roet (TD)',
          'Enebadeg resis (ma vez kenderc\'hadennezh)',
          'Renk kentañ',
        ]},
        { type: 'h2', text: 'Taoliñoù poulloù' },
        { type: 'p', text: 'Ur formula a c\'hall dougañ meur a daol poulloù. Ar c\'hlañvourien a zo repartiiet etre pep taol hervez o renk etre-taol.' },
        { type: 'tip', text: 'Ar skoazell pellek (tablet arbitr) a ro teurel notadoù en amzer gwir eus ar c\'haerojù e-pad ar poulloù.' },
      ],
      ca: [
        { type: 'p', text: 'Les poules són mini-tornejos de tots contra tots. Cada tirador s\'enfronta a tots els altres del seu grup. La classificació final determina qui passa al quadre.' },
        { type: 'h2', text: 'Generació de poules' },
        { type: 'p', text: 'BellePoule distribueix automàticament els tiradors en grups de mida òptima segons el nombre de participants. La distribució es pot ajustar manualment a la fase de Preparació.' },
        { type: 'h2', text: 'Introducció de puntuacions' },
        { type: 'ul', items: [
          'Feu clic en una cel·la de la graella per introduir la puntuació',
          'Format: puntuació del tirador en fila vs tirador en columna',
          'V = Victòria, puntuació màx. configurable (defecte: 5)',
          'El guanyador es marca amb V, el perdedor amb la seva puntuació real',
        ]},
        { type: 'h2', text: 'Criteris de classificació' },
        { type: 'ol', items: [
          'Ràtio V/M (victòries sobre combats disputats)',
          'Índex (tocs donats − tocs rebuts)',
          'Tocs donats (TD)',
          'Enfrontament directe (en cas d\'empat)',
          'Classificació inicial',
        ]},
        { type: 'h2', text: 'Rondes de poules' },
        { type: 'p', text: 'Una fórmula pot tenir diverses rondes de poules. Els tiradors es redistribueixen entre rondes segons la seva classificació intermèdia.' },
        { type: 'tip', text: 'La puntuació remota (tauleta àrbitre) permet introduir puntuacions en temps real des de les pistes durant les poules.' },
      ],
    },
  },

  // ─── TABLEAU ────────────────────────────────────────────────────────────────
  {
    id: 'tableau',
    icon: '🏅',
    category: 'phases',
    title: {
      fr: 'Tableau d\'élimination',
      en: 'Elimination Bracket',
      de: 'Ausscheidungsrunde',
      es: 'Cuadro de eliminación',
      'zh-HK': '淘汰賽',
      br: 'Taolenn eliminadur',
      ca: 'Quadre d\'eliminació',
    },
    content: {
      fr: [
        { type: 'p', text: 'Le tableau d\'élimination directe (DE) place les tireurs en bracket selon leur classement de poules. Les perdants sont éliminés jusqu\'à la finale.' },
        { type: 'h2', text: 'Types de tableaux' },
        { type: 'ul', items: [
          'Tableau classique — élimination simple, de 2 à 256 tireurs',
          'Double élimination — les perdants passent dans un bracket repêchage',
          'Petite finale — match pour la 3ème place (configurable)',
        ]},
        { type: 'h2', text: 'Têtes de série' },
        { type: 'p', text: 'Le seeding est automatique selon le classement des poules. Les 4 (ou 8) premiers sont placés comme têtes de série pour éviter de se retrouver trop tôt dans le tableau.' },
        { type: 'h2', text: 'Saisie des scores du tableau' },
        { type: 'ul', items: [
          'Cliquez sur une MatchCard pour ouvrir la saisie',
          'Score max configurable (défaut : 15 pour épée)',
          'Mort subite : en cas d\'égalité au bout du temps, tirage au sort puis score à 1 touche',
          'Cartons : jaune (+1 pt à l\'adversaire), rouge (+1 pt), noir (exclusion)',
        ]},
        { type: 'warning', text: 'Le tableau ne devient accessible qu\'une fois toutes les poules terminées et le classement validé.' },
        { type: 'tip', text: 'Le chronomètre est intégré à chaque match. Raccourci : Espace pour démarrer/pauser.' },
      ],
      en: [
        { type: 'p', text: 'The direct elimination (DE) bracket places fencers according to their pool ranking. Losers are eliminated until the final.' },
        { type: 'h2', text: 'Bracket Types' },
        { type: 'ul', items: [
          'Classic bracket — single elimination, 2 to 256 fencers',
          'Double elimination — losers move to a repechage bracket',
          'Bronze medal match — 3rd place match (configurable)',
        ]},
        { type: 'h2', text: 'Seeding' },
        { type: 'p', text: 'Seeding is automatic based on pool ranking. The top 4 (or 8) are seeded to prevent early high-profile matchups.' },
        { type: 'h2', text: 'Bracket Score Entry' },
        { type: 'ul', items: [
          'Click a MatchCard to open the score entry',
          'Configurable max score (default: 15 for epee)',
          'Sudden death: in case of tie at time, coin toss then 1-touch score',
          'Cards: yellow (+1 pt to opponent), red (+1 pt), black (exclusion)',
        ]},
        { type: 'warning', text: 'The bracket is only accessible once all pools are finished and the ranking has been validated.' },
        { type: 'tip', text: 'A timer is integrated into each match. Shortcut: Space to start/pause.' },
      ],
      de: [
        { type: 'p', text: 'Das direkte Ausscheidungs-Tableau (DE) ordnet Fechter entsprechend ihrer Pool-Rangliste ein. Verlierer scheiden aus, bis zum Finale.' },
        { type: 'h2', text: 'Tableau-Typen' },
        { type: 'ul', items: [
          'Klassisches Tableau — einfache Ausscheidung, 2 bis 256 Fechter',
          'Doppelausscheidung — Verlierer wechseln in ein Hoffnungsrunden-Tableau',
          'Spiel um Platz 3 — konfigurierbar',
        ]},
        { type: 'h2', text: 'Setzung' },
        { type: 'p', text: 'Die Setzung erfolgt automatisch nach der Pool-Rangliste. Die besten 4 (oder 8) werden gesetzt, um frühe Top-Duelle zu vermeiden.' },
        { type: 'h2', text: 'Ergebniseingabe im Tableau' },
        { type: 'ul', items: [
          'Klicken Sie auf eine MatchCard, um die Ergebniseingabe zu öffnen',
          'Konfigurierbares Höchstergebnis (Standard: 15 beim Degen)',
          'Plötzlicher Tod: bei Gleichstand nach Zeit wird ausgelost, dann 1-Treffer',
          'Karten: Gelb (+1 Pt. für Gegner), Rot (+1 Pt.), Schwarz (Ausschluss)',
        ]},
        { type: 'warning', text: 'Das Tableau ist erst zugänglich, wenn alle Pools abgeschlossen und die Rangliste bestätigt wurde.' },
        { type: 'tip', text: 'Eine Stoppuhr ist in jeden Kampf integriert. Kürzel: Leertaste zum Starten/Pausieren.' },
      ],
      es: [
        { type: 'p', text: 'El cuadro de eliminación directa (DE) coloca a los tiradores según su clasificación de poules. Los perdedores son eliminados hasta la final.' },
        { type: 'h2', text: 'Tipos de cuadros' },
        { type: 'ul', items: [
          'Cuadro clásico — eliminación simple, de 2 a 256 tiradores',
          'Doble eliminación — los perdedores pasan a un cuadro de repesca',
          'Tercer puesto — combate por el bronce (configurable)',
        ]},
        { type: 'h2', text: 'Cabezas de serie' },
        { type: 'p', text: 'El seeding es automático según la clasificación de poules. Los 4 (u 8) primeros se colocan como cabezas de serie para evitar enfrentamientos tempranos entre favoritos.' },
        { type: 'h2', text: 'Introducción de puntuaciones en el cuadro' },
        { type: 'ul', items: [
          'Haz clic en una MatchCard para abrir la introducción de puntuación',
          'Puntuación máx. configurable (defecto: 15 para espada)',
          'Muerte súbita: en caso de empate al final del tiempo, sorteo y un toque',
          'Tarjetas: amarilla (+1 pt al rival), roja (+1 pt), negra (exclusión)',
        ]},
        { type: 'warning', text: 'El cuadro solo es accesible una vez que todas las poules han terminado y la clasificación ha sido validada.' },
        { type: 'tip', text: 'El cronómetro está integrado en cada combate. Atajo: Espacio para iniciar/pausar.' },
      ],
      'zh-HK': [
        { type: 'p', text: '直接淘汰賽（DE）根據分組排名安排選手對陣，敗者淘汰直至決賽。' },
        { type: 'h2', text: '賽制類型' },
        { type: 'ul', items: [
          '標準淘汰 — 單敗淘汰，2 至 256 名選手',
          '雙敗淘汰 — 敗者進入復活賽',
          '季軍賽 — 第三名對決（可配置）',
        ]},
        { type: 'h2', text: '種子排列' },
        { type: 'p', text: '種子排列根據分組排名自動生成，前 4（或 8）名作為種子，避免強者過早相遇。' },
        { type: 'h2', text: '淘汰賽成績輸入' },
        { type: 'ul', items: [
          '點擊 MatchCard 開啟成績輸入',
          '最高分可配置（重劍預設：15）',
          '突然死亡：計時結束同分時抽籤，然後一分決勝',
          '牌：黃牌（對手+1分）、紅牌（對手+1分）、黑牌（取消資格）',
        ]},
        { type: 'warning', text: '所有分組賽完成且排名確認後，才能進入淘汰賽。' },
        { type: 'tip', text: '每場比賽內建計時器，快捷鍵：空白鍵開始/暫停。' },
      ],
      br: [
        { type: 'p', text: 'An daolenn eliminadur resis (DE) a lak ar c\'hlañvourien e bracket hervez o renk poulloù. Ar re kollet a zo eliminaet betek ar final.' },
        { type: 'h2', text: 'Seurtadoù daolenn' },
        { type: 'ul', items: [
          'Daolenn klassik — eliminadur eeun, eus 2 da 256 klañvouer',
          'Eliminadur doubl — ar re kollet a ya d\'ur bracket adtreuziñ',
          'Final bihan — match evit ar 3vet lec\'h (kustomizabl)',
        ]},
        { type: 'h2', text: 'Pennreoù rummad' },
        { type: 'p', text: 'Ar seeding a zo emgefreek hervez renk ar poulloù. Ar 4 (pe 8) kentañ a zo laket evel pennreoù rummad.' },
        { type: 'h2', text: 'Pourvezañ notadoù an daolenn' },
        { type: 'ul', items: [
          'Klikit war ur MatchCard evit digeriñ ar pourvezañ',
          'Notenn uhelañ kustomizabl (dre ziouer: 15 evit klezeeg)',
          'Marv soudañ: ma vez kenderc\'hadennezh ec\'h eus tinadurezh, kraouenn ha 1 pouez',
          'Kartelloù: melen (+1 pt d\'an enebour), ruz (+1 pt), du (diviñs)',
        ]},
        { type: 'warning', text: 'N\'haller tizout an daolenn nemet goude ma vez pep poull echuet hag ar renk kadarnaaet.' },
        { type: 'tip', text: 'Un amzer a zo integraet e pep match. Berradur: Barzh evit kregiñ/ehan.' },
      ],
      ca: [
        { type: 'p', text: 'El quadre d\'eliminació directa (DE) col·loca els tiradors segons la seva classificació de poules. Els perdedors són eliminats fins a la final.' },
        { type: 'h2', text: 'Tipus de quadres' },
        { type: 'ul', items: [
          'Quadre clàssic — eliminació simple, de 2 a 256 tiradors',
          'Doble eliminació — els perdedors passen a un quadre de repesca',
          'Tercer lloc — combat pel bronze (configurable)',
        ]},
        { type: 'h2', text: 'Caps de sèrie' },
        { type: 'p', text: 'El seeding és automàtic segons la classificació de poules. Els 4 (o 8) primers es col·loquen com a caps de sèrie per evitar enfrontaments prematurs entre favorits.' },
        { type: 'h2', text: 'Introducció de puntuacions al quadre' },
        { type: 'ul', items: [
          'Feu clic en una MatchCard per obrir la introducció de puntuació',
          'Puntuació màx. configurable (defecte: 15 per a espasa)',
          'Mort sobtada: en cas d\'empat al final del temps, sorteig i un toc',
          'Targetes: groga (+1 pt al rival), vermella (+1 pt), negra (exclusió)',
        ]},
        { type: 'warning', text: 'El quadre només és accessible un cop totes les poules han finalitzat i la classificació ha estat validada.' },
        { type: 'tip', text: 'El cronòmetre està integrat en cada combat. Drecera: Espai per iniciar/pausar.' },
      ],
    },
  },

  // ─── REMOTE ─────────────────────────────────────────────────────────────────
  {
    id: 'remote',
    icon: '📡',
    category: 'remote',
    title: {
      fr: 'Saisie distante',
      en: 'Remote Scoring',
      de: 'Fernwertung',
      es: 'Puntuación remota',
      'zh-HK': '遠端記分',
      br: 'Pourvezañ eus-pell',
      ca: 'Puntuació remota',
    },
    content: {
      fr: [
        { type: 'p', text: 'La saisie distante permet aux arbitres de saisir les scores depuis une tablette ou un smartphone via Wi-Fi. Un serveur Express est intégré à l\'application (port 8066).' },
        { type: 'h2', text: 'Démarrer la saisie distante' },
        { type: 'ol', items: [
          'Cliquez sur "📡 Saisie distante" dans la barre d\'en-tête',
          'Cliquez sur "Démarrer" — le serveur se lance',
          'Notez l\'adresse IP et le port affichés',
          'Sur la tablette arbitre : ouvrez un navigateur et entrez l\'adresse',
          'Entrez le code d\'accès arbitre pour vous connecter',
        ]},
        { type: 'h2', text: 'Interfaces disponibles' },
        { type: 'ul', items: [
          'Arbitre (/areneN/arbitre) — saisie des scores, chronomètre',
          'Arène (/areneN) — affichage public des scores en temps réel',
          'Tableau de bord (/dashboard) — vue d\'ensemble des arènes actives',
          'Kiosque (/kiosk) — affichage en boucle pour écran public',
          'Public (/public) — classement en temps réel',
        ]},
        { type: 'h2', text: 'Mode hors-ligne' },
        { type: 'p', text: 'Les tablettes arbitres disposent d\'un service worker qui met en cache l\'interface. En cas de perte de connexion Wi-Fi, les actions sont mises en file d\'attente et synchronisées automatiquement à la reconnexion.' },
        { type: 'warning', text: 'L\'ordinateur principal et les tablettes doivent être sur le même réseau Wi-Fi local. Le port 8066 ne doit pas être bloqué par le pare-feu.' },
      ],
      en: [
        { type: 'p', text: 'Remote scoring allows referees to enter scores from a tablet or smartphone via Wi-Fi. An Express server is built into the application (port 8066).' },
        { type: 'h2', text: 'Starting Remote Scoring' },
        { type: 'ol', items: [
          'Click "📡 Remote Scoring" in the header bar',
          'Click "Start" — the server launches',
          'Note the displayed IP address and port',
          'On the referee tablet: open a browser and enter the address',
          'Enter the referee access code to connect',
        ]},
        { type: 'h2', text: 'Available Interfaces' },
        { type: 'ul', items: [
          'Referee (/arenaN/arbitre) — score entry, timer',
          'Arena (/arenaN) — public real-time score display',
          'Dashboard (/dashboard) — overview of active arenas',
          'Kiosk (/kiosk) — looping display for public screen',
          'Public (/public) — real-time ranking',
        ]},
        { type: 'h2', text: 'Offline Mode' },
        { type: 'p', text: 'Referee tablets have a service worker that caches the interface. If Wi-Fi is lost, actions are queued and automatically synchronized upon reconnection.' },
        { type: 'warning', text: 'The main computer and tablets must be on the same local Wi-Fi network. Port 8066 must not be blocked by the firewall.' },
      ],
      de: [
        { type: 'p', text: 'Die Fernwertung ermöglicht Schiedsrichtern, Ergebnisse über WLAN per Tablet oder Smartphone einzugeben. Ein Express-Server ist in die Anwendung integriert (Port 8066).' },
        { type: 'h2', text: 'Fernwertung starten' },
        { type: 'ol', items: [
          'Klicken Sie auf „📡 Fernwertung" in der Kopfzeile',
          'Klicken Sie auf „Starten" — der Server startet',
          'Notieren Sie die angezeigte IP-Adresse und den Port',
          'Auf dem Schiedsrichter-Tablet: Browser öffnen und Adresse eingeben',
          'Zugangscode eingeben, um sich zu verbinden',
        ]},
        { type: 'h2', text: 'Verfügbare Oberflächen' },
        { type: 'ul', items: [
          'Schiedsrichter (/areneN/arbitre) — Ergebniseingabe, Stoppuhr',
          'Arena (/areneN) — öffentliche Echtzeit-Anzeige',
          'Dashboard (/dashboard) — Übersicht aller aktiven Pisten',
          'Kiosk (/kiosk) — Endlosanzeige für öffentlichen Bildschirm',
          'Öffentlich (/public) — Echtzeit-Rangliste',
        ]},
        { type: 'h2', text: 'Offline-Modus' },
        { type: 'p', text: 'Schiedsrichter-Tablets haben einen Service Worker, der die Oberfläche zwischenspeichert. Bei WLAN-Verlust werden Aktionen in die Warteschlange gestellt und bei Wiederverbindung synchronisiert.' },
        { type: 'warning', text: 'Der Hauptcomputer und die Tablets müssen sich im selben lokalen WLAN befinden. Port 8066 darf nicht von der Firewall geblockt werden.' },
      ],
      es: [
        { type: 'p', text: 'La puntuación remota permite a los árbitros introducir puntuaciones desde una tablet o smartphone vía Wi-Fi. Un servidor Express está integrado en la aplicación (puerto 8066).' },
        { type: 'h2', text: 'Iniciar puntuación remota' },
        { type: 'ol', items: [
          'Haz clic en "📡 Puntuación remota" en la barra de cabecera',
          'Haz clic en "Iniciar" — el servidor se lanza',
          'Anota la dirección IP y el puerto mostrados',
          'En la tablet árbitro: abre un navegador e introduce la dirección',
          'Introduce el código de acceso del árbitro para conectarte',
        ]},
        { type: 'h2', text: 'Interfaces disponibles' },
        { type: 'ul', items: [
          'Árbitro (/arenaN/arbitre) — introducción de puntuaciones, cronómetro',
          'Arena (/arenaA) — visualización pública en tiempo real',
          'Panel (/dashboard) — vista general de pistas activas',
          'Kiosco (/kiosk) — visualización en bucle para pantalla pública',
          'Público (/public) — clasificación en tiempo real',
        ]},
        { type: 'h2', text: 'Modo sin conexión' },
        { type: 'p', text: 'Las tablets árbitro tienen un service worker que almacena la interfaz en caché. Si se pierde el Wi-Fi, las acciones se encolan y se sincronizan automáticamente al reconectarse.' },
        { type: 'warning', text: 'El ordenador principal y las tablets deben estar en la misma red Wi-Fi local. El puerto 8066 no debe estar bloqueado por el cortafuegos.' },
      ],
      'zh-HK': [
        { type: 'p', text: '遠端記分讓裁判透過 Wi-Fi 使用平板或手機輸入成績，應用程式內建 Express 伺服器（埠 8066）。' },
        { type: 'h2', text: '啟動遠端記分' },
        { type: 'ol', items: [
          '點擊標頭列中的「📡 遠端記分」',
          '點擊「啟動」— 伺服器啟動',
          '記下顯示的 IP 位址和埠',
          '在裁判平板上：開啟瀏覽器並輸入位址',
          '輸入裁判存取碼連線',
        ]},
        { type: 'h2', text: '可用介面' },
        { type: 'ul', items: [
          '裁判 (/areneN/arbitre) — 成績輸入、計時器',
          '賽場 (/areneN) — 即時公開比分顯示',
          '控制台 (/dashboard) — 所有活躍賽場概覽',
          '資訊亭 (/kiosk) — 公共螢幕循環顯示',
          '公開 (/public) — 即時排名',
        ]},
        { type: 'h2', text: '離線模式' },
        { type: 'p', text: '裁判平板有快取介面的 Service Worker。Wi-Fi 中斷時，操作會排入佇列，重新連線後自動同步。' },
        { type: 'warning', text: '主電腦和平板必須在同一個本地 Wi-Fi 網路上，且埠 8066 不得被防火牆封鎖。' },
      ],
      br: [
        { type: 'p', text: 'Ar skoazell pellek a ro da vrezelourien teurel notadoù deus ur tablet pe ur smartphone dre Wi-Fi. Ur servij Express a zo integraet en arloadenn (porzh 8066).' },
        { type: 'h2', text: 'Kregiñ gant ar skoazell pellek' },
        { type: 'ol', items: [
          'Klikit war „📡 Skoazell pellek" el lerc\'hienn' ,
          'Klikit war „Kregiñ" — ar servij a zo lakaet',
          'Notit ar chomlec\'h IP hag ar porzh diskouezet',
          'War ar tablet arbitr: digorit ur merdeer hag enskrivit ar chomlec\'h',
          'Enskrivit ar c\'hod tizout arbitr evit kevreañ',
        ]},
        { type: 'h2', text: 'Etrewebezhioù hegerz' },
        { type: 'ul', items: [
          'Arbitr (/areneN/arbitre) — pourvezañ notadoù, amzerenn',
          'Kaer (/areneN) — diskouez publik notadoù en amzer gwir',
          'Taolenn-stur (/dashboard) — sell hollek war ar c\'haerojù oberiant',
          'Kioskenn (/kiosk) — diskouez en dro evit skramm publik',
          'Publik (/public) — renk en amzer gwir',
        ]},
        { type: 'h2', text: 'Mod hep kevreadenn' },
        { type: 'p', text: 'Tablettennoù arbitr a zo gant ur service worker a ro ar etrewezhenn en tamm-tamm. Ma vez kollet ar Wi-Fi, an oberiadoù a zo lakaet e rummad-gortozadeg hag asanvet en emgefreek pa vez adkevreaet.' },
        { type: 'warning', text: 'Ret eo d\'an urzhiataer pennañ hag ar tablettennoù bezañ war ar memes rouedad Wi-Fi lec\'hel. N\'haller ket stankañ porzh 8066 dre ar mur-tan.' },
      ],
      ca: [
        { type: 'p', text: 'La puntuació remota permet als àrbitres introduir puntuacions des d\'una tauleta o smartphone via Wi-Fi. Un servidor Express està integrat a l\'aplicació (port 8066).' },
        { type: 'h2', text: 'Iniciar puntuació remota' },
        { type: 'ol', items: [
          'Feu clic a "📡 Puntuació remota" a la barra de capçalera',
          'Feu clic a "Iniciar" — el servidor s\'engega',
          'Anoteu l\'adreça IP i el port mostrats',
          'A la tauleta àrbitre: obriu un navegador i introduïu l\'adreça',
          'Introduïu el codi d\'accés de l\'àrbitre per connectar-vos',
        ]},
        { type: 'h2', text: 'Interfícies disponibles' },
        { type: 'ul', items: [
          'Àrbitre (/areneN/arbitre) — introducció de puntuacions, cronòmetre',
          'Arena (/areneN) — visualització pública en temps real',
          'Tauler (/dashboard) — vista general de pistes actives',
          'Quiosc (/kiosk) — visualització en bucle per a pantalla pública',
          'Públic (/public) — classificació en temps real',
        ]},
        { type: 'h2', text: 'Mode sense connexió' },
        { type: 'p', text: 'Les tauletes àrbitre tenen un service worker que emmagatzema la interfície en memòria cau. Si es perd el Wi-Fi, les accions s\'encuen i es sincronitzen automàticament en reconnectar-se.' },
        { type: 'warning', text: 'L\'ordinador principal i les tauletes han d\'estar a la mateixa xarxa Wi-Fi local. El port 8066 no ha d\'estar bloquejat pel tallafoc.' },
      ],
    },
  },

  // ─── FORMULA ────────────────────────────────────────────────────────────────
  {
    id: 'formula',
    icon: '🔧',
    category: 'advanced',
    title: {
      fr: 'Formule personnalisée',
      en: 'Custom Formula',
      de: 'Benutzerdefinierte Formel',
      es: 'Fórmula personalizada',
      'zh-HK': '自訂賽制',
      br: 'Formula personalizet',
      ca: 'Fórmula personalitzada',
    },
    content: {
      fr: [
        { type: 'p', text: 'Le Constructeur de formule permet de créer des enchaînements de phases sur mesure pour des formats de tournoi non standards.' },
        { type: 'h2', text: 'Types de phases' },
        { type: 'ul', items: [
          'Tour de poules — round-robin avec règles d\'avancement',
          'Élimination directe — tableau simple ou double élimination',
          'Classement — phase finale de classement sans élimination',
        ]},
        { type: 'h2', text: 'Règles d\'avancement' },
        { type: 'ul', items: [
          'Tous avancent — pas d\'élimination à cette phase',
          'Top % — ex. 80% des tireurs avancent',
          'Nombre fixe — ex. les 32 premiers',
          'Tableau direct — tous passent dans le tableau',
        ]},
        { type: 'h2', text: 'Critères de classement personnalisés' },
        { type: 'p', text: 'Pour chaque phase de poules, vous pouvez choisir l\'ordre des critères de classement : V/M, Indice, TD, TR, Confrontation directe, Classement initial.' },
        { type: 'h2', text: 'Modèles de formule' },
        { type: 'p', text: 'Enregistrez vos formules comme modèles réutilisables. Les modèles prédéfinis incluent des configurations standard pour 8, 16, 32, 64+ tireurs.' },
        { type: 'tip', text: 'La simulation dans le Constructeur permet de visualiser comment les tireurs seraient répartis avec la formule actuelle, avant de la valider.' },
      ],
      en: [
        { type: 'p', text: 'The Formula Builder allows you to create custom phase sequences for non-standard tournament formats.' },
        { type: 'h2', text: 'Phase Types' },
        { type: 'ul', items: [
          'Pool round — round-robin with advancement rules',
          'Direct elimination — single or double elimination bracket',
          'Classification — final ranking phase without elimination',
        ]},
        { type: 'h2', text: 'Advancement Rules' },
        { type: 'ul', items: [
          'All advance — no elimination at this phase',
          'Top % — e.g. 80% of fencers advance',
          'Fixed number — e.g. top 32',
          'Direct bracket — all move to the bracket',
        ]},
        { type: 'h2', text: 'Custom Ranking Criteria' },
        { type: 'p', text: 'For each pool phase, you can choose the order of ranking criteria: V/M, Index, TS, TR, Direct encounter, Initial seeding.' },
        { type: 'h2', text: 'Formula Templates' },
        { type: 'p', text: 'Save your formulas as reusable templates. Predefined templates include standard configurations for 8, 16, 32, 64+ fencers.' },
        { type: 'tip', text: 'The simulation in the Formula Builder lets you visualize how fencers would be distributed with the current formula before committing.' },
      ],
      de: [
        { type: 'p', text: 'Der Formel-Builder ermöglicht die Erstellung benutzerdefinierter Phasenabfolgen für nicht-standardmäßige Turnierformate.' },
        { type: 'h2', text: 'Phasentypen' },
        { type: 'ul', items: [
          'Pool-Runde — Round-Robin mit Aufstiegsregeln',
          'Direkte Ausscheidung — einfaches oder Doppel-Ausscheidungs-Tableau',
          'Klassifizierung — abschließende Ranglistenphase ohne Ausscheidung',
        ]},
        { type: 'h2', text: 'Aufstiegsregeln' },
        { type: 'ul', items: [
          'Alle steigen auf — keine Ausscheidung in dieser Phase',
          'Top % — z.B. 80% der Fechter steigen auf',
          'Feste Anzahl — z.B. die besten 32',
          'Direktes Tableau — alle wechseln ins Tableau',
        ]},
        { type: 'h2', text: 'Benutzerdefinierte Ranglistenkriterien' },
        { type: 'p', text: 'Für jede Pool-Phase können Sie die Reihenfolge der Kriterien wählen: V/M, Index, GT, GE, Direktbegegnung, Erstrangierung.' },
        { type: 'h2', text: 'Formelvorlagen' },
        { type: 'p', text: 'Speichern Sie Ihre Formeln als wiederverwendbare Vorlagen. Vordefinierte Vorlagen umfassen Standardkonfigurationen für 8, 16, 32, 64+ Fechter.' },
        { type: 'tip', text: 'Die Simulation im Formel-Builder zeigt, wie Fechter mit der aktuellen Formel verteilt würden, bevor Sie bestätigen.' },
      ],
      es: [
        { type: 'p', text: 'El Constructor de fórmulas permite crear secuencias de fases personalizadas para formatos de torneo no estándar.' },
        { type: 'h2', text: 'Tipos de fases' },
        { type: 'ul', items: [
          'Ronda de poules — todos contra todos con reglas de avance',
          'Eliminación directa — cuadro de eliminación simple o doble',
          'Clasificación — fase de clasificación final sin eliminación',
        ]},
        { type: 'h2', text: 'Reglas de avance' },
        { type: 'ul', items: [
          'Todos avanzan — sin eliminación en esta fase',
          'Top % — ej. 80% de los tiradores avanzan',
          'Número fijo — ej. los 32 primeros',
          'Cuadro directo — todos pasan al cuadro',
        ]},
        { type: 'h2', text: 'Criterios de clasificación personalizados' },
        { type: 'p', text: 'Para cada fase de poules, puedes elegir el orden de los criterios: V/M, Índice, TD, TR, Enfrentamiento directo, Clasificación inicial.' },
        { type: 'h2', text: 'Plantillas de fórmula' },
        { type: 'p', text: 'Guarda tus fórmulas como plantillas reutilizables. Las plantillas predefinidas incluyen configuraciones estándar para 8, 16, 32, 64+ tiradores.' },
        { type: 'tip', text: 'La simulación en el Constructor de fórmulas te permite visualizar cómo se distribuirían los tiradores con la fórmula actual antes de confirmar.' },
      ],
      'zh-HK': [
        { type: 'p', text: '賽制生成器可為非標準賽事格式建立自訂賽段序列。' },
        { type: 'h2', text: '賽段類型' },
        { type: 'ul', items: [
          '分組輪次 — 循環賽加晉級規則',
          '直接淘汰 — 單敗或雙敗淘汰',
          '排名賽 — 無淘汰的最終排名賽段',
        ]},
        { type: 'h2', text: '晉級規則' },
        { type: 'ul', items: [
          '全部晉級 — 此賽段無淘汰',
          '前 % — 例如 80% 的選手晉級',
          '固定人數 — 例如前 32 名',
          '直接進入淘汰賽 — 全部進入淘汰賽',
        ]},
        { type: 'h2', text: '自訂排名標準' },
        { type: 'p', text: '每個分組賽段可選擇排名標準順序：V/M、指數、得分、失分、直接對陣、初始種子。' },
        { type: 'h2', text: '賽制模板' },
        { type: 'p', text: '將賽制儲存為可重複使用的模板，預設模板涵蓋 8、16、32、64+ 名選手的標準配置。' },
        { type: 'tip', text: '賽制生成器中的模擬功能可在確認前預覽選手如何依當前賽制分配。' },
      ],
      br: [
        { type: 'p', text: 'Ar Savour Formula a ro krouiñ rummadoù fazioù personalizet evit furmadoù torneoù n\'int ket reizh.' },
        { type: 'h2', text: 'Seurtadoù fazioù' },
        { type: 'ul', items: [
          'Taol poulloù — round-robin gant reolioù ironed',
          'Eliminadur resis — daolenn eeun pe doubl eliminadur',
          'Renk — faz renk dibenn hep eliminadur',
        ]},
        { type: 'h2', text: 'Reolioù ironed' },
        { type: 'ul', items: [
          'An holl a ya war-raok — eliminadur ebet en traoù-se',
          'Krenn % — da sk. 80% eus ar c\'hlañvourien a ya war-raok',
          'Niver reizh — da sk. ar 32 kentañ',
          'Daolenn resis — an holl a ya er daolenn',
        ]},
        { type: 'h2', text: 'Arvesterioù renk personalizet' },
        { type: 'p', text: 'Evit pep faz poulloù e c\'hallit dibab urzh an arvesterioù renk: V/M, Indez, TD, TR, Enebadeg resis, Renk kentañ.' },
        { type: 'h2', text: 'Patromoù formula' },
        { type: 'p', text: 'Enrollit ho formulaoù evel patromoù adrimpladus. Ar patromoù rakdifinet a ginnig kefluniadegoù reizh evit 8, 16, 32, 64+ klañvouer.' },
        { type: 'tip', text: 'Ar simulerezh er Savour a ro gwelout penaos e vefe ranneet ar c\'hlañvourien gant ar formula a-vremañ, a-raok kadarnaat.' },
      ],
      ca: [
        { type: 'p', text: 'El Constructor de fórmules permet crear seqüències de fases personalitzades per a formats de torneig no estàndard.' },
        { type: 'h2', text: 'Tipus de fases' },
        { type: 'ul', items: [
          'Ronda de poules — tots contra tots amb regles d\'avanç',
          'Eliminació directa — quadre d\'eliminació simple o doble',
          'Classificació — fase de classificació final sense eliminació',
        ]},
        { type: 'h2', text: 'Regles d\'avanç' },
        { type: 'ul', items: [
          'Tots avancen — sense eliminació en aquesta fase',
          'Top % — ex. 80% dels tiradors avancen',
          'Nombre fix — ex. els 32 primers',
          'Quadre directe — tots passen al quadre',
        ]},
        { type: 'h2', text: 'Criteris de classificació personalitzats' },
        { type: 'p', text: 'Per a cada fase de poules, podeu triar l\'ordre dels criteris: V/M, Índex, TD, TR, Enfrontament directe, Classificació inicial.' },
        { type: 'h2', text: 'Plantilles de fórmula' },
        { type: 'p', text: 'Deseu les vostres fórmules com a plantilles reutilitzables. Les plantilles predefinides inclouen configuracions estàndard per a 8, 16, 32, 64+ tiradors.' },
        { type: 'tip', text: 'La simulació al Constructor de fórmules us permet visualitzar com es distribuirien els tiradors amb la fórmula actual abans de confirmar.' },
      ],
    },
  },

  // ─── LASER SABRE ────────────────────────────────────────────────────────────
  {
    id: 'laser',
    icon: '⚡',
    category: 'advanced',
    title: {
      fr: 'Sabre Laser',
      en: 'Laser Sabre',
      de: 'Lasersäbel',
      es: 'Sable Láser',
      'zh-HK': '激光軍刀',
      br: 'Gouriz Laser',
      ca: 'Sabre Làser',
    },
    content: {
      fr: [
        { type: 'p', text: 'Le mode Sabre Laser est une variante de l\'escrime sportive avec un système de zones de touches à points variables et un système de cartons spécifique.' },
        { type: 'h2', text: 'Zones de touches' },
        { type: 'ul', items: [
          '🟢 Zone A — touche standard : 1 point',
          '🟡 Zone B — touche zone intermédiaire : 3 points',
          '🔴 Zone C — touche zone cible : 5 points',
        ]},
        { type: 'h2', text: 'Quest Points' },
        { type: 'p', text: 'Le classement des poules en Sabre Laser utilise les "Quest Points" au lieu du ratio V/M standard. Le total des points de zones remplace l\'indice de touches.' },
        { type: 'h2', text: 'Système de cartons' },
        { type: 'p', text: 'Les cartons sont regroupés en 4 groupes de fautes progressives :' },
        { type: 'ul', items: [
          'Groupe 1 — Blanc → Jaune → Jaune (fautes légères)',
          'Groupe 2 — Jaune → Rouge → Rouge (fautes moyennes)',
          'Groupe 3 — Rouge → Exclusion (fautes graves)',
          'Groupe 4 — Exclusion immédiate (brutalité, tricherie)',
        ]},
        { type: 'tip', text: 'Les statistiques par zone (A/B/C) sont disponibles dans l\'onglet Analytics de chaque compétition Sabre Laser.' },
      ],
      en: [
        { type: 'p', text: 'Laser Sabre mode is a variant of sport fencing with a variable-point touch zone system and a specific card system.' },
        { type: 'h2', text: 'Touch Zones' },
        { type: 'ul', items: [
          '🟢 Zone A — standard touch: 1 point',
          '🟡 Zone B — mid zone touch: 3 points',
          '🔴 Zone C — target zone touch: 5 points',
        ]},
        { type: 'h2', text: 'Quest Points' },
        { type: 'p', text: 'Laser Sabre pool ranking uses "Quest Points" instead of the standard V/M ratio. Zone point totals replace the touch index.' },
        { type: 'h2', text: 'Card System' },
        { type: 'p', text: 'Cards are grouped into 4 progressive fault groups:' },
        { type: 'ul', items: [
          'Group 1 — White → Yellow → Yellow (minor faults)',
          'Group 2 — Yellow → Red → Red (moderate faults)',
          'Group 3 — Red → Exclusion (serious faults)',
          'Group 4 — Immediate exclusion (brutality, cheating)',
        ]},
        { type: 'tip', text: 'Per-zone statistics (A/B/C) are available in the Analytics tab of each Laser Sabre competition.' },
      ],
      de: [
        { type: 'p', text: 'Der Lasersäbel-Modus ist eine Fechtvariante mit variablen Trefferzonen-Punkten und einem spezifischen Kartensystem.' },
        { type: 'h2', text: 'Trefferzonen' },
        { type: 'ul', items: [
          '🟢 Zone A — Standardtreffer: 1 Punkt',
          '🟡 Zone B — Mitteltreffer: 3 Punkte',
          '🔴 Zone C — Zieltreffer: 5 Punkte',
        ]},
        { type: 'h2', text: 'Quest Points' },
        { type: 'p', text: 'Die Pool-Rangliste beim Lasersäbel verwendet „Quest Points" statt des Standard-V/M-Verhältnisses. Der Gesamtpunktestand der Zonen ersetzt den Trefferindex.' },
        { type: 'h2', text: 'Kartensystem' },
        { type: 'p', text: 'Karten sind in 4 progressive Fehlergruppen unterteilt:' },
        { type: 'ul', items: [
          'Gruppe 1 — Weiß → Gelb → Gelb (leichte Fehler)',
          'Gruppe 2 — Gelb → Rot → Rot (mittlere Fehler)',
          'Gruppe 3 — Rot → Ausschluss (schwere Fehler)',
          'Gruppe 4 — Sofortiger Ausschluss (Brutalität, Betrug)',
        ]},
        { type: 'tip', text: 'Statistiken pro Zone (A/B/C) sind im Analyse-Reiter jedes Lasersäbel-Wettkampfs verfügbar.' },
      ],
      es: [
        { type: 'p', text: 'El modo Sable Láser es una variante de la esgrima deportiva con un sistema de zonas de toque con puntos variables y un sistema de tarjetas específico.' },
        { type: 'h2', text: 'Zonas de toque' },
        { type: 'ul', items: [
          '🟢 Zona A — toque estándar: 1 punto',
          '🟡 Zona B — toque de zona intermedia: 3 puntos',
          '🔴 Zona C — toque de zona objetivo: 5 puntos',
        ]},
        { type: 'h2', text: 'Quest Points' },
        { type: 'p', text: 'La clasificación de poules en Sable Láser utiliza "Quest Points" en lugar del ratio V/M estándar. El total de puntos de zona sustituye al índice de toques.' },
        { type: 'h2', text: 'Sistema de tarjetas' },
        { type: 'p', text: 'Las tarjetas se agrupan en 4 grupos de faltas progresivas:' },
        { type: 'ul', items: [
          'Grupo 1 — Blanca → Amarilla → Amarilla (faltas leves)',
          'Grupo 2 — Amarilla → Roja → Roja (faltas medias)',
          'Grupo 3 — Roja → Exclusión (faltas graves)',
          'Grupo 4 — Exclusión inmediata (brutalidad, trampa)',
        ]},
        { type: 'tip', text: 'Las estadísticas por zona (A/B/C) están disponibles en la pestaña Análisis de cada competición de Sable Láser.' },
      ],
      'zh-HK': [
        { type: 'p', text: '激光軍刀模式是擊劍運動的變體，採用可變分值觸碰區域系統和特定牌罰系統。' },
        { type: 'h2', text: '觸碰區域' },
        { type: 'ul', items: [
          '🟢 A 區 — 標準觸碰：1 分',
          '🟡 B 區 — 中間區域觸碰：3 分',
          '🔴 C 區 — 目標區域觸碰：5 分',
        ]},
        { type: 'h2', text: 'Quest Points' },
        { type: 'p', text: '激光軍刀的分組排名使用「Quest Points」代替標準 V/M 比率，各區域總分取代觸碰指數。' },
        { type: 'h2', text: '牌罰系統' },
        { type: 'p', text: '牌罰分為 4 個遞進違規組：' },
        { type: 'ul', items: [
          '第 1 組 — 白→黃→黃（輕微違規）',
          '第 2 組 — 黃→紅→紅（中度違規）',
          '第 3 組 — 紅→取消資格（嚴重違規）',
          '第 4 組 — 立即取消資格（暴力、作弊）',
        ]},
        { type: 'tip', text: '每個激光軍刀比賽的分析分頁中可查看各區域（A/B/C）統計數據。' },
      ],
      br: [
        { type: 'p', text: 'Ar mod Gouriz Laser a zo ur variant eus ar klezeourezh sportif gant ur sistem zonoù pouezioù kemmadus ha ur sistem kartelloù spesifik.' },
        { type: 'h2', text: 'Zonoù pouezioù' },
        { type: 'ul', items: [
          '🟢 Zon A — pouez reizh: 1 poent',
          '🟡 Zon B — pouez zon etre-daou: 3 poent',
          '🔴 Zon C — pouez tachenn: 5 poent',
        ]},
        { type: 'h2', text: 'Quest Points' },
        { type: 'p', text: 'Renk ar poulloù er Gouriz Laser a implij „Quest Points" e-lec\'h ar rapport V/M reizh. Hollad ar pouezioù zon a zisplec\'h an indez.' },
        { type: 'h2', text: 'Sistem kartelloù' },
        { type: 'p', text: 'Ar kartelloù a zo rummet e 4 strollad fazioù irennant:' },
        { type: 'ul', items: [
          'Strollad 1 — Gwenn → Melen → Melen (fazioù bihan)',
          'Strollad 2 — Melen → Ruz → Ruz (fazioù etre-daou)',
          'Strollad 3 — Ruz → Diviñs (fazioù bras)',
          'Strollad 4 — Diviñs emgefreek (gwallvezer, tricher)',
        ]},
        { type: 'tip', text: 'Ar stadegoù dre zon (A/B/C) a zo hegerz en ivinell Analytikoù pep genstrivadeg Gouriz Laser.' },
      ],
      ca: [
        { type: 'p', text: 'El mode Sabre Làser és una variant de l\'esgrima esportiva amb un sistema de zones de toc amb punts variables i un sistema de targetes específic.' },
        { type: 'h2', text: 'Zones de toc' },
        { type: 'ul', items: [
          '🟢 Zona A — toc estàndard: 1 punt',
          '🟡 Zona B — toc de zona intermèdia: 3 punts',
          '🔴 Zona C — toc de zona objectiu: 5 punts',
        ]},
        { type: 'h2', text: 'Quest Points' },
        { type: 'p', text: 'La classificació de poules al Sabre Làser utilitza "Quest Points" en lloc de la ràtio V/M estàndard. El total de punts de zona substitueix l\'índex de tocs.' },
        { type: 'h2', text: 'Sistema de targetes' },
        { type: 'p', text: 'Les targetes s\'agrupen en 4 grups de faltes progressives:' },
        { type: 'ul', items: [
          'Grup 1 — Blanca → Groga → Groga (faltes lleus)',
          'Grup 2 — Groga → Vermella → Vermella (faltes mitjanes)',
          'Grup 3 — Vermella → Exclusió (faltes greus)',
          'Grup 4 — Exclusió immediata (brutalitat, trampa)',
        ]},
        { type: 'tip', text: 'Les estadístiques per zona (A/B/C) estan disponibles a la pestanya Analítica de cada competició de Sabre Làser.' },
      ],
    },
  },

  // ─── EXPORT ─────────────────────────────────────────────────────────────────
  {
    id: 'export',
    icon: '📤',
    category: 'advanced',
    title: {
      fr: 'Import & Export',
      en: 'Import & Export',
      de: 'Import & Export',
      es: 'Importar y Exportar',
      'zh-HK': '匯入與匯出',
      br: 'Ezporzhadur & Enporzhadur',
      ca: 'Importar i Exportar',
    },
    content: {
      fr: [
        { type: 'h2', text: 'Formats d\'export' },
        { type: 'ul', items: [
          'PDF — classement, poules, tableau (personnalisable via Paramètres → PDF)',
          'CSV — données brutes pour tableur',
          'JSON — export complet de la compétition',
          'XML — format FFE standard',
          '.BPM — format natif BellePoule (sauvegarde complète)',
        ]},
        { type: 'h2', text: 'Export PDF personnalisé' },
        { type: 'p', text: 'Dans Paramètres → Personnaliser les PDF, vous pouvez configurer : couleurs, logo du club, sections à inclure, titre personnalisé. Les templates sont exportables/importables en JSON.' },
        { type: 'h2', text: 'Formats d\'import' },
        { type: 'ul', items: [
          'CSV tireurs — Nom, Prénom, Club, Licence, Classement, Nationalité',
          'XML FFE — format standard de la fédération française',
          'FFE Connect — import direct depuis l\'API fédérale',
          '.BPM — réouverture d\'une compétition sauvegardée',
        ]},
        { type: 'h2', text: 'Sync cloud' },
        { type: 'p', text: 'BellePoule supporte la synchronisation chiffrée (AES-GCM) avec Dropbox, Google Drive et OneDrive. Configurez la sync dans Paramètres → Cloud Sync.' },
        { type: 'warning', text: 'Le format .BPM est le seul format qui préserve l\'intégralité de la compétition (scores, cartons, historique des matchs). Utilisez-le pour les sauvegardes.' },
      ],
      en: [
        { type: 'h2', text: 'Export Formats' },
        { type: 'ul', items: [
          'PDF — ranking, pools, bracket (customizable via Settings → PDF)',
          'CSV — raw data for spreadsheets',
          'JSON — full competition export',
          'XML — standard FFE format',
          '.BPM — native BellePoule format (full backup)',
        ]},
        { type: 'h2', text: 'Custom PDF Export' },
        { type: 'p', text: 'In Settings → Customize PDFs, you can configure: colors, club logo, included sections, custom title. Templates are exportable/importable as JSON.' },
        { type: 'h2', text: 'Import Formats' },
        { type: 'ul', items: [
          'CSV fencers — Last name, First name, Club, License, Ranking, Nationality',
          'XML FFE — standard French federation format',
          'FFE Connect — direct import from the federal API',
          '.BPM — reopen a saved competition',
        ]},
        { type: 'h2', text: 'Cloud Sync' },
        { type: 'p', text: 'BellePoule supports encrypted sync (AES-GCM) with Dropbox, Google Drive, and OneDrive. Configure sync in Settings → Cloud Sync.' },
        { type: 'warning', text: 'The .BPM format is the only format that preserves the entire competition (scores, cards, match history). Use it for backups.' },
      ],
      de: [
        { type: 'h2', text: 'Exportformate' },
        { type: 'ul', items: [
          'PDF — Rangliste, Pools, Tableau (anpassbar über Einstellungen → PDF)',
          'CSV — Rohdaten für Tabellenkalkulationen',
          'JSON — vollständiger Wettkampfexport',
          'XML — Standard-FFE-Format',
          '.BPM — natives BellePoule-Format (Vollsicherung)',
        ]},
        { type: 'h2', text: 'Benutzerdefinierter PDF-Export' },
        { type: 'p', text: 'In Einstellungen → PDFs anpassen können Sie konfigurieren: Farben, Vereinslogo, enthaltene Abschnitte, benutzerdefinierten Titel. Vorlagen sind als JSON ex-/importierbar.' },
        { type: 'h2', text: 'Importformate' },
        { type: 'ul', items: [
          'CSV Fechter — Nachname, Vorname, Verein, Lizenz, Rangliste, Nationalität',
          'XML FFE — Standard-Format des französischen Verbands',
          'FFE Connect — Direktimport über die Verbands-API',
          '.BPM — gespeicherten Wettkampf wieder öffnen',
        ]},
        { type: 'h2', text: 'Cloud-Synchronisation' },
        { type: 'p', text: 'BellePoule unterstützt verschlüsselte Synchronisation (AES-GCM) mit Dropbox, Google Drive und OneDrive. Konfigurieren Sie die Sync unter Einstellungen → Cloud Sync.' },
        { type: 'warning', text: 'Das .BPM-Format ist das einzige Format, das den gesamten Wettkampf (Ergebnisse, Karten, Kampfhistorie) bewahrt. Für Sicherungen verwenden.' },
      ],
      es: [
        { type: 'h2', text: 'Formatos de exportación' },
        { type: 'ul', items: [
          'PDF — clasificación, poules, cuadro (personalizable en Ajustes → PDF)',
          'CSV — datos brutos para hoja de cálculo',
          'JSON — exportación completa de la competición',
          'XML — formato estándar FFE',
          '.BPM — formato nativo BellePoule (copia de seguridad completa)',
        ]},
        { type: 'h2', text: 'Exportación PDF personalizada' },
        { type: 'p', text: 'En Ajustes → Personalizar PDFs puedes configurar: colores, logo del club, secciones incluidas, título personalizado. Las plantillas son exportables/importables en JSON.' },
        { type: 'h2', text: 'Formatos de importación' },
        { type: 'ul', items: [
          'CSV tiradores — Apellido, Nombre, Club, Licencia, Clasificación, Nacionalidad',
          'XML FFE — formato estándar de la federación francesa',
          'FFE Connect — importación directa desde la API federal',
          '.BPM — reabrir una competición guardada',
        ]},
        { type: 'h2', text: 'Sincronización en la nube' },
        { type: 'p', text: 'BellePoule soporta sincronización cifrada (AES-GCM) con Dropbox, Google Drive y OneDrive. Configura la sync en Ajustes → Cloud Sync.' },
        { type: 'warning', text: 'El formato .BPM es el único que preserva toda la competición (puntuaciones, tarjetas, historial de combates). Úsalo para las copias de seguridad.' },
      ],
      'zh-HK': [
        { type: 'h2', text: '匯出格式' },
        { type: 'ul', items: [
          'PDF — 排名、分組、淘汰賽（可在設定→PDF 自訂）',
          'CSV — 試算表用原始數據',
          'JSON — 完整比賽匯出',
          'XML — 標準 FFE 格式',
          '.BPM — BellePoule 原生格式（完整備份）',
        ]},
        { type: 'h2', text: '自訂 PDF 匯出' },
        { type: 'p', text: '在設定→自訂 PDF 中可配置：顏色、俱樂部標誌、包含章節、自訂標題。模板可以 JSON 格式匯出/匯入。' },
        { type: 'h2', text: '匯入格式' },
        { type: 'ul', items: [
          'CSV 選手 — 姓氏、名字、俱樂部、執照、排名、國籍',
          'XML FFE — 法國聯盟標準格式',
          'FFE Connect — 直接從聯盟 API 匯入',
          '.BPM — 重新開啟已儲存的比賽',
        ]},
        { type: 'h2', text: '雲端同步' },
        { type: 'p', text: 'BellePoule 支援與 Dropbox、Google Drive 和 OneDrive 的加密同步（AES-GCM），在設定→Cloud Sync 中配置。' },
        { type: 'warning', text: '.BPM 格式是唯一完整保留比賽資料（成績、牌罰、賽事歷史）的格式，請用於備份。' },
      ],
      br: [
        { type: 'h2', text: 'Furmadoù ezporzhadur' },
        { type: 'ul', items: [
          'PDF — renk, poulloù, daolenn (kustomizabl dre Parametroù → PDF)',
          'CSV — roadennoù dav evit daolenn-niverennoù',
          'JSON — ezporzhadur klok ar genstrivadeg',
          'XML — furmad reizh FFE',
          '.BPM — furmad nativel BellePoule (marc\'h-enklask klok)',
        ]},
        { type: 'h2', text: 'Ezporzhadur PDF personalizet' },
        { type: 'p', text: 'E Parametroù → Personaliziñ ar PDFoù e c\'hallit kefluniañ: livioù, logo ar klub, rannioù da bignañ, titl personalizet. Ar patromoù a zo ezporzhiadus/enporzhiadus e JSON.' },
        { type: 'h2', text: 'Furmadoù enporzhadur' },
        { type: 'ul', items: [
          'CSV klañvourien — Anv, Kentanv, Klub, Roadenn, Renk, Broadelezh',
          'XML FFE — furmad reizh kevredigezh Frañs',
          'FFE Connect — enporzhadur resis eus an API kevredel',
          '.BPM — addigeriñ ur genstrivadeg savetaet',
        ]},
        { type: 'h2', text: 'Sinkroniezh cloud' },
        { type: 'p', text: 'BellePoule a skor sinkroniezh kryptaet (AES-GCM) gant Dropbox, Google Drive hag OneDrive. Kefluniit ar sinkroniezh e Parametroù → Cloud Sync.' },
        { type: 'warning', text: 'Ar furmad .BPM eo an hini nemetañ a ra gant an hollad ar genstrivadeg (notadoù, kartelloù, istor ar matchoù). Implij anezhañ evit ar marc\'hadurioù.' },
      ],
      ca: [
        { type: 'h2', text: 'Formats d\'exportació' },
        { type: 'ul', items: [
          'PDF — classificació, poules, quadre (personalitzable a Configuració → PDF)',
          'CSV — dades en brut per a fulls de càlcul',
          'JSON — exportació completa de la competició',
          'XML — format estàndard FFE',
          '.BPM — format natiu BellePoule (còpia de seguretat completa)',
        ]},
        { type: 'h2', text: 'Exportació PDF personalitzada' },
        { type: 'p', text: 'A Configuració → Personalitzar PDFs podeu configurar: colors, logotip del club, seccions incloses, títol personalitzat. Les plantilles són exportables/importables en JSON.' },
        { type: 'h2', text: 'Formats d\'importació' },
        { type: 'ul', items: [
          'CSV tiradors — Cognom, Nom, Club, Llicència, Classificació, Nacionalitat',
          'XML FFE — format estàndard de la federació francesa',
          'FFE Connect — importació directa des de l\'API federal',
          '.BPM — tornar a obrir una competició desada',
        ]},
        { type: 'h2', text: 'Sincronització al núvol' },
        { type: 'p', text: 'BellePoule admet sincronització xifrada (AES-GCM) amb Dropbox, Google Drive i OneDrive. Configureu la sync a Configuració → Cloud Sync.' },
        { type: 'warning', text: 'El format .BPM és l\'únic que preserva tota la competició (puntuacions, targetes, historial de combats). Useu-lo per a les còpies de seguretat.' },
      ],
    },
  },

  // ─── SHORTCUTS ──────────────────────────────────────────────────────────────
  {
    id: 'shortcuts',
    icon: '⌨️',
    category: 'advanced',
    title: {
      fr: 'Raccourcis clavier',
      en: 'Keyboard Shortcuts',
      de: 'Tastenkürzel',
      es: 'Atajos de teclado',
      'zh-HK': '鍵盤快捷鍵',
      br: 'Berradurioù klavier',
      ca: 'Dreceres de teclat',
    },
    content: {
      fr: [
        { type: 'h2', text: 'Globaux' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Palette de commandes' },
          { key: '?', desc: 'Aide raccourcis clavier' },
          { key: 'Ctrl+N', desc: 'Nouvelle compétition' },
          { key: 'Échap', desc: 'Fermer / Annuler' },
          { key: 'Ctrl+S', desc: 'Sauvegarder' },
          { key: 'Ctrl+Z', desc: 'Annuler (Undo)' },
          { key: 'Ctrl+Y', desc: 'Refaire (Redo)' },
          { key: 'F5', desc: 'Rafraîchir les données' },
        ]},
        { type: 'h2', text: 'Navigation' },
        { type: 'kbd', shortcuts: [
          { key: 'Tab', desc: 'Navigation entre champs' },
          { key: '↑ ↓', desc: 'Naviguer dans une liste' },
          { key: 'Entrée', desc: 'Valider / Ouvrir' },
          { key: 'Alt+P', desc: 'Aller aux poules' },
          { key: 'Alt+T', desc: 'Aller au tableau' },
          { key: 'Alt+R', desc: 'Aller aux résultats' },
        ]},
        { type: 'h2', text: 'Compétition' },
        { type: 'kbd', shortcuts: [
          { key: 'Espace', desc: 'Démarrer/Pause le chronomètre' },
        ]},
      ],
      en: [
        { type: 'h2', text: 'Global' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Command palette' },
          { key: '?', desc: 'Keyboard shortcuts help' },
          { key: 'Ctrl+N', desc: 'New competition' },
          { key: 'Esc', desc: 'Close / Cancel' },
          { key: 'Ctrl+S', desc: 'Save' },
          { key: 'Ctrl+Z', desc: 'Undo' },
          { key: 'Ctrl+Y', desc: 'Redo' },
          { key: 'F5', desc: 'Refresh data' },
        ]},
        { type: 'h2', text: 'Navigation' },
        { type: 'kbd', shortcuts: [
          { key: 'Tab', desc: 'Field navigation' },
          { key: '↑ ↓', desc: 'Navigate a list' },
          { key: 'Enter', desc: 'Validate / Open' },
          { key: 'Alt+P', desc: 'Go to pools' },
          { key: 'Alt+T', desc: 'Go to bracket' },
          { key: 'Alt+R', desc: 'Go to results' },
        ]},
        { type: 'h2', text: 'Competition' },
        { type: 'kbd', shortcuts: [
          { key: 'Space', desc: 'Start/Pause timer' },
        ]},
      ],
      de: [
        { type: 'h2', text: 'Global' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Befehlspalette' },
          { key: '?', desc: 'Tastenkürzel-Hilfe' },
          { key: 'Ctrl+N', desc: 'Neuer Wettkampf' },
          { key: 'Esc', desc: 'Schließen / Abbrechen' },
          { key: 'Ctrl+S', desc: 'Speichern' },
          { key: 'Ctrl+Z', desc: 'Rückgängig' },
          { key: 'Ctrl+Y', desc: 'Wiederholen' },
          { key: 'F5', desc: 'Daten aktualisieren' },
        ]},
        { type: 'h2', text: 'Navigation' },
        { type: 'kbd', shortcuts: [
          { key: 'Tab', desc: 'Feldnavigation' },
          { key: '↑ ↓', desc: 'Liste navigieren' },
          { key: 'Enter', desc: 'Bestätigen / Öffnen' },
          { key: 'Alt+P', desc: 'Zu Pools' },
          { key: 'Alt+T', desc: 'Zum Tableau' },
          { key: 'Alt+R', desc: 'Zu Ergebnissen' },
        ]},
        { type: 'h2', text: 'Wettkampf' },
        { type: 'kbd', shortcuts: [
          { key: 'Leertaste', desc: 'Stoppuhr starten/pausieren' },
        ]},
      ],
      es: [
        { type: 'h2', text: 'Globales' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Paleta de comandos' },
          { key: '?', desc: 'Ayuda de atajos de teclado' },
          { key: 'Ctrl+N', desc: 'Nueva competición' },
          { key: 'Esc', desc: 'Cerrar / Cancelar' },
          { key: 'Ctrl+S', desc: 'Guardar' },
          { key: 'Ctrl+Z', desc: 'Deshacer' },
          { key: 'Ctrl+Y', desc: 'Rehacer' },
          { key: 'F5', desc: 'Actualizar datos' },
        ]},
        { type: 'h2', text: 'Navegación' },
        { type: 'kbd', shortcuts: [
          { key: 'Tab', desc: 'Navegación entre campos' },
          { key: '↑ ↓', desc: 'Navegar en una lista' },
          { key: 'Enter', desc: 'Validar / Abrir' },
          { key: 'Alt+P', desc: 'Ir a poules' },
          { key: 'Alt+T', desc: 'Ir al cuadro' },
          { key: 'Alt+R', desc: 'Ir a resultados' },
        ]},
        { type: 'h2', text: 'Competición' },
        { type: 'kbd', shortcuts: [
          { key: 'Espacio', desc: 'Iniciar/Pausar cronómetro' },
        ]},
      ],
      'zh-HK': [
        { type: 'h2', text: '全局' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: '命令面板' },
          { key: '?', desc: '鍵盤快捷鍵說明' },
          { key: 'Ctrl+N', desc: '新增比賽' },
          { key: 'Esc', desc: '關閉 / 取消' },
          { key: 'Ctrl+S', desc: '儲存' },
          { key: 'Ctrl+Z', desc: '復原' },
          { key: 'Ctrl+Y', desc: '重做' },
          { key: 'F5', desc: '重新整理資料' },
        ]},
        { type: 'h2', text: '導航' },
        { type: 'kbd', shortcuts: [
          { key: 'Tab', desc: '欄位導航' },
          { key: '↑ ↓', desc: '瀏覽清單' },
          { key: 'Enter', desc: '確認 / 開啟' },
          { key: 'Alt+P', desc: '前往分組' },
          { key: 'Alt+T', desc: '前往淘汰賽' },
          { key: 'Alt+R', desc: '前往結果' },
        ]},
        { type: 'h2', text: '比賽' },
        { type: 'kbd', shortcuts: [
          { key: '空白鍵', desc: '開始/暫停計時器' },
        ]},
      ],
      br: [
        { type: 'h2', text: 'Hollek' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Palet urzhioù' },
          { key: '?', desc: 'Skoazell berradurioù klavier' },
          { key: 'Ctrl+N', desc: 'Kenstrivadeg nevez' },
          { key: 'Esc', desc: 'Serriñ / Nullañ' },
          { key: 'Ctrl+S', desc: 'Saveteiñ' },
          { key: 'Ctrl+Z', desc: 'Nullañ (Undo)' },
          { key: 'Ctrl+Y', desc: 'Adober (Redo)' },
          { key: 'F5', desc: 'Aozañ ar roadennoù' },
        ]},
        { type: 'h2', text: 'Levezon' },
        { type: 'kbd', shortcuts: [
          { key: 'Tab', desc: 'Levezon etre burujoù' },
          { key: '↑ ↓', desc: 'Levezon e ur roll' },
          { key: 'Enankañ', desc: 'Kadarnaat / Digeriñ' },
          { key: 'Alt+P', desc: 'Mont d\'ar poulloù' },
          { key: 'Alt+T', desc: 'Mont d\'an daolenn' },
          { key: 'Alt+R', desc: 'Mont d\'ar disoc\'hoù' },
        ]},
        { type: 'h2', text: 'Kenstrivadeg' },
        { type: 'kbd', shortcuts: [
          { key: 'Barzh', desc: 'Kregiñ/Ehan ar c\'hronomet' },
        ]},
      ],
      ca: [
        { type: 'h2', text: 'Globals' },
        { type: 'kbd', shortcuts: [
          { key: 'Ctrl+K', desc: 'Paleta d\'ordres' },
          { key: '?', desc: 'Ajuda de dreceres de teclat' },
          { key: 'Ctrl+N', desc: 'Nova competició' },
          { key: 'Esc', desc: 'Tancar / Cancel·lar' },
          { key: 'Ctrl+S', desc: 'Desar' },
          { key: 'Ctrl+Z', desc: 'Desfer' },
          { key: 'Ctrl+Y', desc: 'Refer' },
          { key: 'F5', desc: 'Actualitzar dades' },
        ]},
        { type: 'h2', text: 'Navegació' },
        { type: 'kbd', shortcuts: [
          { key: 'Tab', desc: 'Navegació entre camps' },
          { key: '↑ ↓', desc: 'Navegar en una llista' },
          { key: 'Enter', desc: 'Validar / Obrir' },
          { key: 'Alt+P', desc: 'Anar a poules' },
          { key: 'Alt+T', desc: 'Anar al quadre' },
          { key: 'Alt+R', desc: 'Anar a resultats' },
        ]},
        { type: 'h2', text: 'Competició' },
        { type: 'kbd', shortcuts: [
          { key: 'Espai', desc: 'Iniciar/Pausar cronòmetre' },
        ]},
      ],
    },
  },
];

// ─── Category labels ─────────────────────────────────────────────────────────

export const CATEGORY_LABELS: Record<string, Record<WikiLang, string> & { icon: string }> = {
  start: {
    fr: 'Démarrage', en: 'Getting Started', de: 'Einstieg', es: 'Inicio',
    'zh-HK': '入門', br: 'Kregiñ', ca: 'Inici', icon: '🚀',
  },
  competition: {
    fr: 'Compétition', en: 'Competition', de: 'Wettkampf', es: 'Competición',
    'zh-HK': '比賽', br: 'Kenstrivadeg', ca: 'Competició', icon: '🏆',
  },
  phases: {
    fr: 'Phases', en: 'Phases', de: 'Phasen', es: 'Fases',
    'zh-HK': '賽制', br: 'Traoùioù', ca: 'Fases', icon: '📋',
  },
  remote: {
    fr: 'Saisie', en: 'Remote', de: 'Fernwertung', es: 'Remoto',
    'zh-HK': '遠端', br: 'Pellek', ca: 'Remot', icon: '📡',
  },
  advanced: {
    fr: 'Avancé', en: 'Advanced', de: 'Erweitert', es: 'Avanzado',
    'zh-HK': '進階', br: 'Araoket', ca: 'Avançat', icon: '🔧',
  },
};

export const VALID_LANGS: WikiLang[] = ['fr', 'en', 'de', 'es', 'zh-HK', 'br', 'ca'];

export function getLang(language: string): WikiLang {
  return VALID_LANGS.includes(language as WikiLang) ? (language as WikiLang) : 'en';
}

export function getTitle(article: WikiArticle, lang: WikiLang): string {
  return article.title[lang] ?? article.title['en'];
}

export function getContent(article: WikiArticle, lang: WikiLang) {
  return article.content[lang] ?? article.content['en'];
}

export const SEARCH_PLACEHOLDER: Record<WikiLang, string> = {
  fr: 'Rechercher…', en: 'Search…', de: 'Suchen…', es: 'Buscar…',
  'zh-HK': '搜尋…', br: 'Klask…', ca: 'Cercar…',
};

export const NO_RESULTS_LABEL: Record<WikiLang, string> = {
  fr: 'Aucun résultat', en: 'No results', de: 'Keine Ergebnisse', es: 'Sin resultados',
  'zh-HK': '無結果', br: "Disoc'h ebet", ca: 'Cap resultat',
};
